### ISSUE TITLE
Clan Tags doesn't show on my tab list

### ISSUE THREAD

**Issue by Naomon** [marcelo-mason/SimpleClans#233]
Hello guys,

I'm trying to use the SimpleClans on my server a long time, and all the things go right exceptly of Clan Tags on my TabList. I've tried many versions (2.4.1, 2.4.4, 2.5) and in all versions the Clan Tag doesn't appear on my TabList. Anyone can help me?
![printerror](https://cloud.githubusercontent.com/assets/9681696/4999531/3bf627b4-69ca-11e4-8d35-416cff2b9a01.jpg)

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/wiki/Displaying-the-clan-tag-on-the-tablist
