### ISSUE TITLE
Support for Holographic Displays/ Holographic Scoreboards

### ISSUE THREAD

**Issue by Peter234679** [marcelo-mason/SimpleClans#250]
Hi! Is there anyway that you could add support for Holographic displays/ Holographic ScoreBoards (http://dev.bukkit.org/bukkit-plugins/holographic-scoreboard/ , http://dev.bukkit.org/bukkit-plugins/holographic-displays/) ? Mainly I want the /clan leaderboard command to be able to show up, in its current state trying to run the command is not possible and says the command cannot be executed. After talking with the Developer from Holographic Scoreboards he says that the issue most likely is on the SimpleClans end.

**Comment by Peter234679** [comment]
Any progress??

**Comment by Rofuera** [comment]
I'm also looking forward to it! :+1:

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/77483259-7d580100-6e06-11ea-9fd0-9b89f1791855.png)

I don't remember editing the leaderboard command, but it's working now...

**Comment by FrozenBeard** [comment]
Brilliant Idea! But using CMI Holgorams instead so not needing an entire second plugin to have holograms!

**Comment by RoinujNosde** [comment]
> But using CMI Holgorams instead so not needing an entire second plugin to have holograms!

Then CMI Holograms should add a way to create holograms from commands (this is what Holographic ScoreBoards does).

**Comment by FrozenBeard** [comment]
> 
> 
> > But using CMI Holgorams instead so not needing an entire second plugin to have holograms!
> 
> Then CMI Holograms should add a way to create holograms from commands (this is what Holographic ScoreBoards does).

It does.

**Comment by RoinujNosde** [comment]
> It does.

Good to know!
Does it also center aligns the text? A left align would be perfect here...
