### ISSUE TITLE
2 Chat related requests

### ISSUE THREAD

**Issue by Murabitos** [marcelo-mason/SimpleClans#268]
First off, thanks for the chat compatability mode!
1. I'd like for Simpleclans to pull the user's group color from groupmanager and use it for their standard tag color (as an option in the config)
2. I'd like the ability to move the clan tag after the user's group tag (also using groupmanager)

EDIT: Can the prevention of color changes be made if I deny the ability to use any color? or will that mess up the default color too?

Thanks.

**Comment by RoinujNosde** [comment]
This probably can be achieved using a chat plugin that supports PlaceholderAPI.

**Comment by FrozenBeard** [comment]
@Murabitos Dont be using groupmanager in 2020, LuckPerms even imports it
