### ISSUE TITLE
Clan Members and Online-Mode: False.

### ISSUE THREAD

**Issue by ProjectMine** [marcelo-mason/SimpleClans#273]
When I put online-mode false in server.properties, every time that I restart the server all clans appear without members.

I think it´s about uuids and stuff of Mojang.

I´m using Spigot 1.8.3

Is there any solution?

Thanks for all.

**Comment by phaed420** [comment]
Tough one, UUIDs change when offline/online.  This would require saving both, thus a major change on the way things are currently architected.  The cost/reward for this is pretty low, not many people switch back and forth.  Will probably not fix this.
