### ISSUE TITLE
[Feature Request] KDR grinding prevention

### ISSUE THREAD

**Issue by Murabitos** [marcelo-mason/SimpleClans#276]
Players can kill people over and over to get as much KDR as they want. It would be nice to set a cap of X amount of times that a player can kill the same person with it still changing their KDR. This should not count for deaths.

**Comment by Her-Craving** [comment]
I'd appreciate if you could add me on skype (bla_Saige433) or email me (ashafton@gmail.com) so that we can talk in private. I'm willing to pay you to add some of these feature requests I'm making, along with an update to your sign logger plugin.

**Comment by phaed420** [comment]
Cool, added you on Skype.

**Comment by erik1988** [comment]
I would like this feature. Also some plugins that records KDR have a time limit on when you can get the kill-stat for the same player again. So let say you kill the same player within 10 min (or whatever), it will not record the kill, on a server with few players this could be an alternative.
