### ISSUE TITLE
Ally chat not seen when simpleclans.admin.all-seeing-eye permission node given

### ISSUE THREAD

**Issue by Her-Craving** [marcelo-mason/SimpleClans#277]
Ally chat not seen when simpleclans.admin.all-seeing-eye permission node is given. Only normal clan chat can be. 

Also come on skype

**Comment by Her-Craving** [comment]
It isn't working.

**Comment by matgsan** [comment]
Check your permissions!

**Comment by Her-Craving** [comment]
Is there a different permission for seeing ally chat and seeing clan chat?

**Comment by matgsan** [comment]
nope

**Comment by Her-Craving** [comment]
I can see clan chat, but not ally chat... Hmm..
