### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Bodyash** [marcelo-mason/SimpleClans#286]
Hi, i`m using home hosting on win7.
My launch script is:
chcp 65001
"%ProgramFiles%\Java\jre1.8.0_31\bin\java.exe" -server -Xms8G -Xmx22G -Dfile.encoding=UTF8 -jar spigot.jar

So with that config i can read Cyrillic in cmd, but when i`m translating any plugin - i must change encoding of lang.yml or lang.properties to UTF-8 or UTF-8 without BOM.

When i tried to translate this plugin - i found a small promlem. There is no lang file inside folder. So i found it inside .jar and overwrite it with russian translation. Launch server and found strange symbol. Next stem - i`ve change encoding to UTF-8. No changes :c There is strange symbols again, but not the same as first time.

How i can translate it?

**Comment by Bodyash** [comment]
http://i.imgur.com/7BVi9lq.png UTF-8
http://i.imgur.com/7ipwziF.png ANSI

How i trying to change lang:
Open SimpleClans.jar with Winrar and overwrite lang.properties with my own file. File is translated using Notepad++. 

Plz, help with it.

**Comment by Bodyash** [comment]
and one more. There is no 
lang = getConfig().getString("setting.languagel");
in SettingsManager.java
So changing language in config.yml has no effect.

So there is only one way to change language - change it inside SimleClans.jar.
There is any way, for example, player.sendMessage(); - force send it in UTF-8, like in lang file?

**Comment by marcelo-mason** [comment]
Details here http://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle

**Comment by marcelo-mason** [comment]
Let me know if this works.

**Comment by Bodyash** [comment]
It WORKS! Ty much!

**Comment by Bodyash** [comment]
Now Commands Doesnt react at all, i can use only /clan to see plugin help, and /more command. There is no reaction to any other commands. /clan home - nothing happens + error in console

http://rghost.ru/7St6GzkL2 My translation file

Error in console: for any /clan command, for example /clan list

http://pastebin.com/dFaix10R

**Comment by marcelo-mason** [comment]
Here is a yml version of your language file.  You can replace the one in **server/plugins/SimpleClans/language.yml** with it.

http://pastebin.com/TjmKxgcb
