### ISSUE TITLE
Huge LagSpike onPlayerDeath, onPlayerJoin and onPlayerQuit Event

### ISSUE THREAD

**Issue by DDevilISL** [marcelo-mason/SimpleClans#287]
Simple clans is cause a massive 3.000 ms lag on my server, i've tried to change the spigot version, but it still happens, help plz :( awesome pl btw :)

**Comment by MDelgadoCCM** [comment]
Need more info than this.  How do you know the lag is coming from SC?

**Comment by DDevilISL** [comment]
I used /timings from spigot, also, when i disable simple clans, the issue is gone :(

**Comment by MDelgadoCCM** [comment]
Can you post said timings?

**Comment by MDelgadoCCM** [comment]
Also before anything, are you running the dev versions of SC from the Jenkins?  Cause one of the recent issues that were fixed was a timing issue that sounds very similar to what you are describing.

**Comment by DDevilISL** [comment]
I actually did use the dev version, but it was when i was trying to fix it, when I first found de bug i was using the legacy version of SC
  I'll have to generate another timing, because i lost the previous one Kkk, but i'll send it right away when i've generated it :)

**Comment by DDevilISL** [comment]
Found one of the original timings, this one is 1,305ms but others got to reach 3k ms
http://timings.aikar.co/?url=11175322
