### ISSUE TITLE
Clan tag ideas

### ISSUE THREAD

**Issue by DevilDonkey69** [marcelo-mason/SimpleClans#291]
These are a few clan tag ideas that you should add.
1.) In Call of Duty they have a Clan system, But the clan tag starts out as white then you can level up your clan, and when you level it up you can get a gold clan tag, and when you level up some more you can get a red clan tag, so you should add something like that level up Clan tags.

2.) If you don't like that, could you just add a permission to have a certain color clan tag.

I hope you like these ideas and could add them in.

**Comment by RoinujNosde** [comment]
> 2.) If you don't like that, could you just add a permission to have a certain color clan tag.

How to do it:
Listen to ClanCreateEvent:
Since it is a new clan, change its name color to white using setColorTag();

In every kill or in a timer task (or whatever else):
Check clan's level using some conditions of yours.
Change its name color if necessary.
