### ISSUE TITLE
Land claiming system

### ISSUE THREAD

**Issue by AkamDev** [marcelo-mason/SimpleClans#293]
Hi,
Everything is good with the plugin except that it does not have a claiming system to claim land,
Server owners should have an option in the config to enable or disable the system.

and i know about PreciousStones but thats not what i am looking for.

**Comment by marcelo-mason** [comment]
Don't have the time to create such comlex a feature.  You are welcome to find a dev that can create it and issue a pull request.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/wiki/Giving-clan-members-access-to-GriefPrevention-lands
