### ISSUE TITLE
Many Bugs

### ISSUE THREAD

**Issue by livebullet** [marcelo-mason/SimpleClans#297]
There are a lot of bugs that are making this plugin unusable.

Firstly, I have vault and CraftConomy3, yet the cost to create a clan does not work.

Secondly, once i send an alliance request, it constantly spams the other clan asking for an alliance. Same thing happens with rivalries.

How do player verify their clan on their own?

How to party chat?

**Comment by marcelo-mason** [comment]
You need Vault for economy support.  
There is a setting for limiting the request messages, look in the config.
You can disable clan verification in the config also.
What do you mean by party chat?

**Comment by livebullet** [comment]
I meant to say alliance chat.

Also, they other clan accepted the alliance request yet it still spams them, they accepted 5+ times and now I am allied with them 5 times, and it is still asking them.

**Comment by marcelo-mason** [comment]
What version are you running? The dev versions from Jenkins or the one from BukkitDev?

**Comment by livebullet** [comment]
The BukkitDev version.

**Comment by RoinujNosde** [comment]
Is this still an issue?
