### ISSUE TITLE
No commands

### ISSUE THREAD

**Issue by Scorpionvssub** [marcelo-mason/SimpleClans#302]
Okay im using 1.8.7 and i loaded this plugin in, it loads up as it should, creates a config a help thing and all BUT when i do /help simpleclans it wont show any commands and on /clan it says it doesnt know any?

**Comment by Scorpionvssub** [comment]
this plugin is exacly what im looking for specially due to some perms can just not be given to disallow stuff like a sethome for clans making it more clans style no faction lookalike

**Comment by RoinujNosde** [comment]
Is this still an issue?
