### ISSUE TITLE
Hey, I cannot use simpleclan commands on commandblock, why?

### ISSUE THREAD

**Issue by flgmjr** [marcelo-mason/SimpleClans#304]
when I try to do it, it just says "unknown command, type /help for help".

**Comment by marcelo-mason** [comment]
Can you give me an example?

**Comment by flgmjr** [comment]
first of all, i just downloaded the latest version on jenkins, and part of the issue is fixed. Now it says the correct usage of the sentence.
You probably know that in the command block, the term @p is for the nearest player, but when i try to use it , it says the correct way of using the command. Maybe simpleclans just doesn't support de usage of @p, @r, etc.?

**Comment by flgmjr** [comment]
PS.: i already tried using "sudo"

**Comment by marcelo-mason** [comment]
Can you give me an example of the command you are using?

**Comment by flgmjr** [comment]
i am using : "sudo -u flgmjr clan place @p H4GRed

**Comment by marcelo-mason** [comment]
Its a bug in Spigot.  I tested with [Spigot 1.8.7](http://tcpr.ca/download/spigot/spigot-1.8.7-R0.1-SNAPSHOT-latest.jar) and it works fine.  Its broken on Spigot 1.8.

**Comment by flgmjr** [comment]
thank you man! And i am bothering you with this because i tested a lot of plugins but your's is just the best one i found! Thank you again!
