### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.5.3 - on /. <chat>

### ISSUE THREAD

**Issue by Nentify** [marcelo-mason/SimpleClans#306]
http://pastebin.com/rxbcpiy0

I'm running KCauldron + MC 1.7.10

Also, `display-chat-tags: false` is set, but players still have clan tags before their usernames in chat.

Edit: This error occurs on most clan commands, not just /.

Edit 2: Also getting this error, and messages are being sent in both clan chat and global chat. http://pastebin.com/iTKtch4w

**Comment by marcelo-mason** [comment]
Upgrade to the latest dev version, see if that fixes it.

**Comment by Nentify** [comment]
All fixed, thanks so much <3
