### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by Leuggim** [marcelo-mason/SimpleClans#308]
Hi
I'm running spigot 1.8.3, plugin version 2.5.3
and I'm getting this, spamming in my console:
thank you

09.07 12:06:43 [Server] INFO ... 16 more
09.07 12:06:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
09.07 12:06:43 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
09.07 12:06:43 [Server] INFO at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[?:?]
09.07 12:06:43 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerCommandPreprocess(SCPlayerListener.java:110) ~[?:?]
09.07 12:06:43 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1295) ~[?:?]
09.07 12:06:43 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1390) ~[?:?]
09.07 12:06:43 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.sendToAllSeeing(ClanManager.java:1403) ~[?:?]
09.07 12:06:43 [Server] INFO Caused by: java.lang.NullPointerException
09.07 12:06:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
09.07 12:06:43 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:972) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1129) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:43 [Server] INFO org.bukkit.event.EventException
09.07 12:06:43 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.5.3
09.07 12:06:37 [Multicraft] Skipped 1 lines due to rate limit (30/s)
09.07 12:06:37 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:37 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
09.07 12:06:37 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
09.07 12:06:37 [Server] INFO at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[?:?]
09.07 12:06:37 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerCommandPreprocess(SCPlayerListener.java:110) ~[?:?]
09.07 12:06:37 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1295) ~[?:?]
09.07 12:06:37 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1390) ~[?:?]
09.07 12:06:37 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.sendToAllSeeing(ClanManager.java:1403) ~[?:?]
09.07 12:06:37 [Server] INFO Caused by: java.lang.NullPointerException
09.07 12:06:37 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
09.07 12:06:37 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
09.07 12:06:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:972) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1129) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:36 [Server] INFO org.bukkit.event.EventException
09.07 12:06:36 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.5.3
09.07 12:06:33 [Multicraft] Skipped 1 lines due to rate limit (30/s)
09.07 12:06:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
09.07 12:06:32 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
09.07 12:06:32 [Server] INFO at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[?:?]
09.07 12:06:32 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.listeners.SCPlayerListener.onPlayerCommandPreprocess(SCPlayerListener.java:110) ~[?:?]
09.07 12:06:32 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1295) ~[?:?]
09.07 12:06:32 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.processClanChat(ClanManager.java:1390) ~[?:?]
09.07 12:06:32 [Server] INFO at net.sacredlabyrinth.phaed.simpleclans.managers.ClanManager.sendToAllSeeing(ClanManager.java:1403) ~[?:?]
09.07 12:06:32 [Server] INFO Caused by: java.lang.NullPointerException
09.07 12:06:32 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_45]
09.07 12:06:32 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_45]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:972) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1129) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[custom.jar:git-Spigot-4c7d0c0-7d020a7]
09.07 12:06:32 [Server] INFO org.bukkit.event.EventException
09.07 12:06:32 [Server] ERROR Could not pass event PlayerCommandPreprocessEvent to SimpleClans v2.5.3

**Comment by Leuggim** [comment]
'-'

**Comment by RoinujNosde** [comment]
Is this still an issue?
