### ISSUE TITLE
Clan Chat Not Working

### ISSUE THREAD

**Issue by mobilephone2003** [marcelo-mason/SimpleClans#309]
I'm trying everything, but "/." literally gives no feedback, but it doesn't give an invalid command error

Is it still in SimpleClans?

**Comment by marcelo-mason** [comment]
It should be.  I'll test it out later today.

**Comment by mobilephone2003** [comment]
Using Build #125 and all builds prior, including Legacy

**Comment by mobilephone2003** [comment]
Never mind, I was just using the /. command as I assumed it was a toggle. Turns out its /. <Chatgoeshere> and /. join
