### ISSUE TITLE
Bank Value Cleared

### ISSUE THREAD

**Issue by Gavster4** [marcelo-mason/SimpleClans#312]
We've had an issue where at least with one clan their bank value is odd. The bulletin board shows 6k deposited, then 950 deposited then 1k withdrawn. In-game they show a clan balance of 0 when a member does /clan bank status.

Any ideas what might be happening?

**Comment by Gavster4** [comment]
An update to this issue. We discovered it happens when a player (particularly this test was a clan leader) withdraws money from the clan bank but doesn't withdraw the full bank value. The amount is subtracted in the bulletin but the bank value seems to be reset to 0.

**Comment by Gavster4** [comment]
The specific issue is in the bank withdrawl section there is a line:  

setBalance(0);

**Comment by Jack-McKalling** [comment]
Related to PR #322
