### ISSUE TITLE
Alliance request spams after /accept

### ISSUE THREAD

**Issue by Cirquo** [marcelo-mason/SimpleClans#319]
So, when a player does /clan ally add <clan>, it sends the request twice. When the opposite clan's leader types /accept (or whatever), they become allies. However, after this the request keeps spamming the opposite clan's leader, and he may ally that clan as many times as he wants to.

The spam is very annoying, I hope this can be fixed soon.

Thank you

**Comment by TGWaffles** [comment]
Note - I've seen this many times in other servers, this is quite a large issue.

**Comment by RoinujNosde** [comment]
Is this still an issue?

**Comment by Cirquo** [comment]
I wouldn't know, haven't used the plugin for one and a half year. I remember I fixed it by removing the seen message. The spamming was still going on in console, I think.

**Comment by RoinujNosde** [comment]
Probably fixed, can't reproduce.
