### ISSUE TITLE
I invite people to join the staff clan They Have Not changed their usernames and it will not allow them to join

### ISSUE THREAD

**Issue by gravestristen** [marcelo-mason/SimpleClans#321]
3:53:55 PM EDT CONSOLE: [INFO] giantawesomemeep issued server command: /clan invite jmanrock
3:54:03 PM EDT CONSOLE: [INFO] giantawesomemeep issued server command: /clan invite jmanrock0801
3:54:03 PM EDT CONSOLE: [INFO] Jmanrock0801 issued server command: /whois
3:54:03 PM EDT CONSOLE: [INFO] Command 'whois' conflicts with plugin 'Essentials vTeamCity', McMyAdmin will not receive this command. Command will be sent to 'Essentials vTeamCity' instead.
3:54:06 PM EDT CONSOLE: [INFO] Jmanrock0801 issued server command: /whois Jmanrock0801
3:54:06 PM EDT CONSOLE: [INFO] Command 'whois' conflicts with plugin 'Essentials vTeamCity', McMyAdmin will not receive this command. Command will be sent to 'Essentials vTeamCity' instead.
3:54:08 PM EDT CONSOLE: [INFO] Jmanrock0801 issued server command: /accept
3:54:08 PM EDT CONSOLE: [INFO] Jmanrock0801 tried command: accept

**Comment by RoinujNosde** [comment]
Is this still an issue?
