### ISSUE TITLE
Citizens lose their city to upgrade 1.7.2 -> 1.8.1

### ISSUE THREAD

**Issue by ReNNoN** [marcelo-mason/SimpleClans#325]
Hello,
I have a serious problem:

I've always used SimpleClans-Legacy 1.7.2.
I have a server with many clans, (too).

But I have a problem when I try to upgrade to 1.7.2 SimpleClans-Legacy to SimpleClans 1.8.3! -> citizens lose their clans.
- Clans with 100 people are left with 10 people.
- Clans with 100 people are left with 2 people.
  and more...

I have reviewed the "purge", but not that. He is very active people, all disappear.

what can I do?

Thank you

**Comment by RoinujNosde** [comment]
Is this still an issue?
