### ISSUE TITLE
Get Rid of Precious Stones

### ISSUE THREAD

**Issue by CapitalArk** [marcelo-mason/SimpleClans#326]
Hello, now I personally love this plugin. The idea of clans, rivalries, wars, alliances, kdr, etc. It is epic, unlike any other plugins. The only downside is I wish there was one more thing. Now we can agree this plugin is almost similar to Factions, but better. The only downside to this plugin is the ability to create Clan Plots. 

What is a Clan Plot?

Well it's an area of land that is protected, that can only be edited by members of the clan. 

Now yes, this plugin does work with PreciousStones and it solely relies on that plugin for clan plot protections. But I find it very difficult to use this plugin, too many commands. Now if somehow SimpleClans could create there own method for allowing clan leaders to plot out a land for their clan, that would be fantastic. By doing this as well, clans who go to war should be able to Raid each others bases, and the victor receives the land as a trophy. Theres so much you can add to make this Plugin even better, and these are just my suggestions.

Thank You.

**Comment by SmokeArrow** [comment]
so just get factions plugin
