### ISSUE TITLE
Can you remove the clan tag before he name or just the period?

### ISSUE THREAD

**Issue by XHarderX** [marcelo-mason/SimpleClans#327]
is there any possible way to disable or get rid of the period in the clan tag when you talk? I use permissionsex and it doesn't look very good with the ranks with the period at the end. If you could help me or add this. It would be a big help. Thanks

**Comment by MorgansVault** [comment]
Simple go into the config file and change the period to something, maybe a bracket for example: [ or ]

Unfortunately, I do not see a way to disable or reorder the tags altogether as I'd like to move it after the "Admin" group I have... or not have clan tags show at all.
