### ISSUE TITLE
Sc_clans table blanked out.

### ISSUE THREAD

**Issue by Gavster4** [marcelo-mason/SimpleClans#328]
We had a separate server issue and needed to recover from it. After correcting the issue and bringing things back up we discovered that while the other tables are fine, the sc_clans table has been blanked out. sc_players still has playerdata with tags, but the bank balances, etc. were lost. We are using the db file and plan to change to MySQL but wanted to determine if there is a bug causing this issue before we proceed much further given the amount of data lost in that table. Interestingly enough, this behavior seems to have been replicated on a second server as well although it was just a development server and much less important.

Is there a condition that will cause this issue?

Thanks!

**Comment by RoinujNosde** [comment]
Is this still an issue?
