### ISSUE TITLE
Crackshot Support

### ISSUE THREAD

**Issue by coolMJW** [marcelo-mason/SimpleClans#330]
You should add Crackshot support for Kills, Deaths, Friendly Fire, Vitals and etc.

Also a customisable lang file would be awesome!

**Comment by RoinujNosde** [comment]
If you are still interested, answer with more details.

**Comment by FrozenBeard** [comment]
If you do decide to do this, dont use CrackShot, Quality Armory took over and is much better.
https://www.spigotmc.org/resources/quality-armory.47561/

**Comment by RoinujNosde** [comment]
To decide, I'm gonna need more details. Like how will the hook work? What does it mean by supporting vitals? Does Crackshot increases a player's life?

**Comment by FrozenBeard** [comment]
I don't use either at present, I just wanted to make sure that if any support was added it wasn't for CrackShot but Quality Amory. 
We are tempted in the future though as were a Pirate Server and flintlocks might be cool!
