### ISSUE TITLE
Clan /accept

### ISSUE THREAD

**Issue by ZielZane** [marcelo-mason/SimpleClans#332]
On my server timgaming.com the /accept command does not go through when I'm invited, please look into it, thanks.

**Comment by i9hdkill** [comment]
This happens when sc does not update the username after a player changed it.
Manually update the username in the database and reload the plugin to fix this issue for this player

**Comment by RoinujNosde** [comment]
Still an issue?

**Comment by RoinujNosde** [comment]
Duplicate of #331
