### ISSUE TITLE
I need to change the mysql port, but no option!

### ISSUE THREAD

**Issue by FabioZumbi12** [marcelo-mason/SimpleClans#334]
On config theres no option to port, and if i use "localhost:MyPort" dont connect too. Please add a port option!

**Comment by marcelo-mason** [comment]
You can add the port on the host.  Like you mention:  "localhost:3306".  Maybe its not connecting due to another problem?

**Comment by FabioZumbi12** [comment]
Yes, the plugin remove the '' around hostname:port string and dont connect!

I adding in this momento an option on your config, i have forked, if i test and work, i open a pull request, and you see is all ok too.

**Comment by FabioZumbi12** [comment]
I have added, with success the port and worked. here the pull: https://github.com/marcelo-mason/SimpleClans/pull/335

And more on think, the reload command is disabled? I didnt find any erros or causes to do not work. I get the unknow command as player and as console.

Thanks :)

**Comment by marcelo-mason** [comment]
merged the pull request
