### ISSUE TITLE
Great Plugin But...

### ISSUE THREAD

**Issue by Tekiad** [marcelo-mason/SimpleClans#337]
Hello, it´s a simple issue, but it´s a big problem... A lot of people wants this plugin in Spanish, I can help with the translate but not alone :) I wish it too <3

**Comment by PiLogic** [comment]
Just extract the jar with winrar(or other software) and edit the language.yml

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/tree/master/src/main/resources
Create a file called language-es.yml with your translation (or part of it)
