### ISSUE TITLE
Global friendly fire always auto

### ISSUE THREAD

**Issue by RoinujNosde** [marcelo-mason/SimpleClans#341]
Plugin version: 2.5.5
Server version: Spigot 1.8.3 (git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT))
Issue: The "/clan globalff allow" command doesn't work. Friendly fire is still managed by the clan.

**Comment by marcelo-mason** [comment]
Will look into it.

**Comment by RoinujNosde** [comment]
Why is not global ff being checked if true in lines 292, 299, 306 and 314? (https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/listeners/SCEntityListener.java)

**Comment by marcelo-mason** [comment]
thanks
