### ISSUE TITLE
UUID fetching

### ISSUE THREAD

**Issue by NoChanceSD** [marcelo-mason/SimpleClans#344]
Could you make your UUID fetcher asynchronous? I had some issues where it hangs the server for some time. Also, i don't know if you support offline mode but i had this issue on an offline mode server, which shouldn't even happen since there is no need to fetch UUID from mojang.

**Comment by PiLogic** [comment]
Yeah, i'm having the same issue, spigot watchdog thread stopping the server because the uuid fetching takes so long on the main thread. i'm trying to make it async without break the implementation, but it's a hard work :(

**Comment by RoinujNosde** [comment]
Is this still an issue?
