### ISSUE TITLE
Possible SQL Column Change?

### ISSUE THREAD

**Issue by anthonyloukinas** [marcelo-mason/SimpleClans#345]
By default, sc_clans and sc_players both have a "name" column that are obviously different, one being the players name and one being the clans name respectively. Would there be anyway to modify this to be like player_name, clan_name or something? I'm coding a web platform and it would make 10 times easier to work with. Thanks :)

**Comment by knight-ryu12** [comment]
possibly change it. But need change Mysql code.
2015/12/21 15:08 "Anthony Loukinas" <notifications@github.com>:

**Comment by anthonyloukinas** [comment]
I could possibly make the changes, but i was having trouble locating all the depends. ;/

**Comment by marcelo-mason** [comment]
Not feasible to change this for everyone.  People have massive databases and I imagine other tools that depend on the names being what they currently are.

**Comment by marcelo-mason** [comment]
All dependencies are already included in the pom.xml by the way.  Maven should build without issues.
