### ISSUE TITLE
[Future Request] About Maven Repo

### ISSUE THREAD

**Issue by knight-ryu12** [marcelo-mason/SimpleClans#350]
I want this API/Plugin to inject with maven repo.
Maven will make this plugin lot more easier.
EDIT: BadEnglish. Sorry. :)

**Comment by marcelo-mason** [comment]
Maven should be working, check pom.xm

The release builds can be found here in artifactory:

http://107.170.92.11/artifactory/plugins-release-local/net/sacredlabyrinth/phaed/simpleclans/SimpleClans/

**Comment by RoboMWM** [comment]
Seems like you got a new server for jenkins, but is the maven repo setup as well?
