### ISSUE TITLE
language.yml not copied from jar.

### ISSUE THREAD

**Issue by Fortifier42** [marcelo-mason/SimpleClans#353]
I noticed when I loaded the plugin for the first time that the config was copied successfully, however the language.yml file was not. causing a FileNotFound exception.

**Comment by RoinujNosde** [comment]
Still an issue?

**Comment by Fortifier42** [comment]
Not a clue, this is 18 months ago.

**Comment by RoinujNosde** [comment]
> this is 18 months ago.

This is why I asked :)

**Comment by Fortifier42** [comment]
I don't use it or play minecraft anymore, I dunno mate :) You can try it can't you?

**Comment by RoinujNosde** [comment]
Minecraft is such a great game...
