### ISSUE TITLE
Clan members limit

### ISSUE THREAD

**Issue by CrazyDev** [marcelo-mason/SimpleClans#362]
I'm sorry for my English , I'm from Brazil .

please , implements limit players in the clan .

example:

in config.yml

players_per_clan : 10

**Comment by CrazyDev** [comment]
waiting....

**Comment by marcelo-mason** [comment]
No longer doing active development on this.  You are welcome to code it and send a Pull Request though.

**Comment by CrazyDev** [comment]
thanks

**Comment by CrazyDev** [comment]
however, tell me about this piece in the config

clan :
   max- length: 25
