### ISSUE TITLE
Essentials /back integration Request

### ISSUE THREAD

**Issue by fahlur** [marcelo-mason/SimpleClans#363]
I've noticed the fact that simple clans doesn't work with essentials /back. This would be a great addition if I could please request such a feature.

I mean it would be as simple as hooking into essentials and using this when the player is teleported

ess3 is the set variable for when you hook into essentials.. (making that clear lol)

ess3.getUser(player).setLastLocation();

**Comment by fahlur** [comment]
dead project i'm assuming? sigh...

**Comment by marcelo-mason** [comment]
Read the disclaimer on the README.md

**Comment by RoinujNosde** [comment]
@fahlur try to set register-back-in-listener as true. (Essentials config)

**Comment by fahlur** [comment]
Prob is, the server gives /jumpto access, which causes a huge problem to that and the wilderness portal as well. Not worried about it anymore to be honest. I mean its literally 1 hook with 1 line of code, but no its fine.

Thanks you, appreciate the help RoinjNosde!
