### ISSUE TITLE
/clan does not work 

### ISSUE THREAD

**Issue by Teekzz** [marcelo-mason/SimpleClans#386]
/clan doesn't work for anyone besides op. I'm new to configing files so its probably a pretty easy fix... please help.

Update : it says insufficient permission when someone tries to use it

**Comment by marcelo-mason** [comment]
Yep you need to set up the permissions.

**Comment by Teekzz** [comment]
I figured, but there's nothing in the config file that fixes is.... so where do I go?

**Comment by marcelo-mason** [comment]
Google on how to set up permissions on a bukkit plugin.
