### ISSUE TITLE
[Feature request] Dynmap support

### ISSUE THREAD

**Issue by erik1988** [marcelo-mason/SimpleClans#388]
Title is pretty self explanatory, I know it used to be a plugin like this before but that one is outdated. 

I would like is to be able to show the clan homes on the map.

**Comment by RoinujNosde** [comment]
https://github.com/RoinujNosde/Dynmap-SimpleClans/releases

**Comment by FrozenBeard** [comment]
Yes @RoinujNosde nice one!
