### ISSUE TITLE
/. join crashes server

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#391]
Chat control is one of the most popular chat management plugins, it has its own hover over formatting the same as deluxe chat, can you please support ChatControl formatting to allow sending what Clan a person is in on hover over of thier username.

**Comment by FrozenBeard** [comment]
After implementation its already supported. But there is an issue with the chatcontrol "formatted" option being enabled for the global chat to display chat with hover over tooltips and actions and SimpleClans /. join clan join command, where both the messages go to the clan chat and the global.

**Comment by RoinujNosde** [comment]
>  But there is an issue with the chatcontrol "formatted" option being enabled for the global chat to display chat with hover over tooltips and actions and SimpleClans /. join clan join command, where both the messages go to the clan chat and the global.

Can you rewrite it? I don't understand...

**Comment by FrozenBeard** [comment]
Sorry that was very hard to understand now I re-read it, I didn't understand myself!
It was when a player toggled talking in clan chat, it would display to both the global and to the crew chat. 
I cant remember if it was /crew join or /crew chat to toggle it, it was so long ago.
Neither command seems to work now, maybe it was removed?

**Comment by RoinujNosde** [comment]
I don't know. I've never used it.
So this request is "off"?

**Comment by FrozenBeard** [comment]
As In I cant use the command, and its not displaying in my /crew (what I renamed it). Its been so long I cant remember even how to toggle chat, I had a guy modify the source to allow /c maybe he removed it? If theres not a way to toggle clan chatting, then Im requesting that.

**Comment by RoinujNosde** [comment]
I think there is a way to toggle.
Uh... /. join and /. leave
@marcelo-mason can you confirm the commands?

**Comment by marcelo-mason** [comment]
I believe so, but I haven't tested them lately, maybe they don't work?

**Comment by FrozenBeard** [comment]
Holy shit! That was it, and I now remember why I removed the permission. It just crashed my server!
oh my god, I did it on my live server.

**Comment by marcelo-mason** [comment]
Can you paste here the error log, that would help with debugging what the problem was.

**Comment by FrozenBeard** [comment]
First thing I checked, It didn't leave any detail.
I ran the command it it completely froze everything, the only messages I have are from my wrapper:
```
2017-08-09 00:50:36 # server might have crashed: not accepting connections or wrong port is being pinged. -- restarting.
2017-08-09 00:50:36 # stopping survival (caused by not accepting connections)
2017-08-09 00:50:36 # server might have crashed: not accepting accepting console commands or crash-unknown-cmd-message is not set -- restarting.
2017-08-09 00:50:36 # stopping survival (caused by crashed)
2017-08-09 00:51:36 # killing survival (caused by crashed)
```

**Comment by marcelo-mason** [comment]
Which one, the leave one?

**Comment by FrozenBeard** [comment]
I did /. join.

**Comment by FrozenBeard** [comment]
Im using the latest Build of PaperSpigot If that helps anything.

**Comment by marcelo-mason** [comment]
Great, thanks for the info.  @RoinujNosde leave it to you.

**Comment by FrozenBeard** [comment]
its something deadly serious, as Its completely screwed my dedicated server, im having to reboot it, its completely locked up with a core on 100% cpu and nothing is running in htop/top.

**Comment by RoinujNosde** [comment]
Are you sure it's SimpleClans crashing? Could you try without other plugins?

**Comment by FrozenBeard** [comment]
100% when I ran that command. Ill test it on my test server at home. as that royally killed everything.

**Comment by RoinujNosde** [comment]
Ok, Thanks.

**Comment by RoinujNosde** [comment]
![2017-08-22_18 10 25](https://user-images.githubusercontent.com/6441328/29587756-42dbf728-8765-11e7-81f6-fcd7ab9b000a.png)
It works as expected.
Spigot: 1.8.8
SimpleClans: latest build

Are you sure it is SimpleClans? Are you using the latest build?

**Comment by FrozenBeard** [comment]
@RoinujNosde Spigot 1.8.8, Yeah you're a little behind buddy. it crashes in 1.12.1.

**Comment by RoinujNosde** [comment]
![2017-08-31_19 18 29](https://user-images.githubusercontent.com/6441328/29947679-50204358-8e81-11e7-93da-4ce67b28fd15.png)

**Comment by RoinujNosde** [comment]
Please reopen if you have new info.

**Comment by FrozenBeard** [comment]
Using the latest dev version seems to have fixed this! I changed my chat command to /c for chat, and players can use /c join and /c leave fine now, maybe it had something to do with using the period.

**Comment by RoinujNosde** [comment]
I don't know if it was the dot, I had tested it.
But I'm glad it is fixed ;)
