### ISSUE TITLE
It crops every plugin message

### ISSUE THREAD

**Issue by be-nazarenko** [marcelo-mason/SimpleClans#392]
Hello! I'm using the latest build of SimpleClans from Jenkins (6). I'm trying to change some messages for my server. When I try to make message longer it doesn't show me full message. It looks like this (/clan list):
language.yml — http://imgur.com/FTtwvcz
In-game message — http://imgur.com/wDjA2gi
I hope you'll fix.

**Comment by RoinujNosde** [comment]
Still an issue?

**Comment by InterStena** [comment]
@RoinujNosde yes, I tried it right now with build #20. Still the same.

**Comment by RoinujNosde** [comment]
Ok. Can you test removing the apostrophes? (At I'm and it's)

**Comment by luiswenner** [comment]
this problem also happens to me, i try to translate into my language and i need a few more lines to finish the translation, and this causes several texts to be cut off and not displayed
