### ISSUE TITLE
clan tag in player tag

### ISSUE THREAD

**Issue by Marrarus** [marcelo-mason/SimpleClans#393]
hey,
i wnated to ask if its possible to add as feature the option to show the clantag in a players name. so that it got shown over the player self.
(if this feature is no option i would also be thankfull for a plugin link who would give me that option)

**Comment by RoinujNosde** [comment]
There is this plugin from a brazilian guy: http://gamersboard.com.br/topic/116-heroclantags-12-»-tags-de-clans-no-placar-e-no-tab/

@marcelo-mason
Close.
