### ISSUE TITLE
Request: Config option to change /. quick chat command.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#395]
1) This command can not be have an alas made as its a special character. 
Most nearly all the commands are customisable apart from this, which is incredibly irritating that its hard coded in, we have had to compile our own verison of the plugin to change ours to /c.

Request: Allow /. be changeable in the configs.

**Comment by FrozenBeard** [comment]
holy snap! dev work happening on simple clans! yes! is there any way this simple addition could be added? then I can start using the latest dev versions! I want to be able to use /c for my players.

**Comment by RoinujNosde** [comment]
This seems easy to implement, but I'm not home this week. When I get back will work on it :)

**Comment by FrozenBeard** [comment]
Fantastic! Any luck? :) im itching to try out the dev on my production!

**Comment by RoinujNosde** [comment]
I'm finishing a project of mine.
I think I will have time this sunday.
