### ISSUE TITLE
Reqquest: Permission node to use colors in tags

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#396]
I want to be able to limit who can use color in their tags, this would be fine if setting color was limited to modtag only, but its not, its also part of creating a clan! so there is no way to limit who can use colors in their clan tag. A permission node would fix this.

**Comment by FrozenBeard** [comment]
Bump! Should be an easy one to implement.

**Comment by RoinujNosde** [comment]
TO DO:
- Add a permission to use colors;
- Check for the permission on modtag;
- Check for the permission on create.

**Comment by FrozenBeard** [comment]
yes! Awesome, thanks man.

**Comment by RoinujNosde** [comment]
No prob
