### ISSUE TITLE
[URGENT] On server restart clans are deleted!

### ISSUE THREAD

**Issue by SmokeArrow** [marcelo-mason/SimpleClans#399]
When I restart my server, I was in a clan. After I joined, it said I wasn't in one. I tried deleting the plugin, restart, install, restart, and joining again. I was using a default config too, with no success. Please fix this issue ASAP! It's a big problem for my server, thanks!

**Comment by matgsan** [comment]
Something in the console?

**Comment by RoinujNosde** [comment]
Still an issue?
