### ISSUE TITLE
[REQUEST] Mineplex Mode (Devs PLEASE make this!)

### ISSUE THREAD

**Issue by w1nst0nDEV** [marcelo-mason/SimpleClans#400]
**REQUEST -** Please consider the following:

Mineplex Mode: 

As people might know, Mineplex has clans servers. Now, say you wanted features that Mineplex had, and SimpleClans offered them! I would adore the developers! You would enable this is the config. Here are the features when Mineplex Mode is enabled:
- Mineplex Messages like Mineplex - Includes stuff like "&9Clans> &7Clan &e(CLANNAME)&7 was created" (Instead of *) or "&6(CLANNAME) &e(USERNAME) &7(MESSAGE)" for chat messages. This means there would be no tagname. ;(
- Another Main Concept - When you start out with a clan you are given 1 energy. Energy depletes everyday by one. If the energy depletes all the way, then the clan's territory is not protected. Get energy by doing /clans energy buy. Whenever a person buys energy, a command is done. This command is in the config. Stuff like {USER} and {ENERGY} are used in the command to explain how much energy a user is buying. Example: command_on_buy: /eco {USER} take 1000, or something rather. take"/clans energy" by itself tells you how much energy you have. If a clan loses its energy, an announcement is broadcasted saying "&9Energy> &e(CLANNAME)'s &7energy has depleted! Go to ((CORDNATES)) for free loot!" or something rather. Another way to access someone else's territory is to gain war points against them. You gain one war point against a clan if you kill one of their members. You lose some if you are killed. If a clan has more than 3 points against you, they are marked as an enemy automatically. If a clan has more than 5 war points against you, every war point counts as 10 minutes of availability towards that clan's territory for the clan that has the war points against them. Whenever the war point is earned, the timer starts for availability. The objective is to not have your energy deplete or lose war points against clans. One more way to get into someone's base is by tnt. If you click with tnt in your hand, it sends out tnt. Tnt explodes the base allowing to come in. This is only available if a clan member is online.
- Clans Features - Throwable TnT, TnT Generators, Mushroom Stew (Gives regeneration for a few seconds.) and possibly (,no, not possible,) Clans Kits with Class Changers (Lengendaries..?)?? At least do the tnt, where you can buy it with /tnt (Command on tnt buy changeable in the config.) or, if you want to, you can do /shop with Throwable TnT, TnT Generators, Mushroom Stew and class armor 
- Clans can use iron doors in their territory.
- /report - /report (Clan) (Reason) - reports a clan to staff members (Hacks or inappropriate builds)
- Other Chat Features and Tab - /cc (Clan Chat) /ac (Ally Chat) - Allows you to turn on clan chat or ally chat. - Clan colors - If you are in a person's clan, their chat color name is &3, enemies are &4, and allies are &2. Staff tags are shown to the far right before anything. Same thing in tab. 
- Staff Mode and Staff Ranks - Change staff with /rank (player) (rank) Normal - Default permissions.    C. Mod (Shown as "&6&lC. Mod) (C. Mod stands for C Mod) - With clan mod, you can blacklist people with /blacklist and access to /reports (Shows a list of reports) (We will get to blacklists later). Admin (Shown as "&4&lAdmin" - /staffmode - Turns you in creative, inventory saved, enchanted diamond in slot 9 named "&aMenu". Bypass any clan protection (Iron Doors and Build). Upon the diamond click, it opens up a GUI with the following items: Sunflower Named "Bypass Shop", Redstone Block named "Reports" and a diamond sword named "Legendaries". All are self explanatory. While in staff mode, in tab and in chat, the "Admin" tag turns into "&a&lSTAFF MODE" and /tp is allowed to be used (Added into clans) - Owner (Shown as &4&lOwner) - Same as Admin.
- Blacklist and Dead Ranks - In the config, you can turn on a type of hardcore mode. If this is enabled, if a user dies, they are turned into a "DEAD" rank, where they are basically spectating in gamemode 3. If all your ONLINE clan users are dead, then their clan territory is available to be used. While in spectator mode, you can teleport to players with a compass or have a clock with "Revive" on it, meaning it takes away 10 energy and revives you (Takes away the "DEAD" Rank and puts you at your clan home). The "Dead" Rank is shown at the far right of their name, like staff tags, in tab and in chat messages. The Blacklist rank is given as a punishment of hacking and what not. As being blacklisted, you do not have any join/leave messages, you can not chat, you are not shown in tab (Except for staff members) and are completely invisible in-game, can not break/place any blocks and are placed as a completely invisible spectator. Staff use the /blacklist command to give these ranks out. /blacklist uses the following format: /blacklist [ADD/REMOVE] [USER] [TIME/PERM] [REASON]. Upon being blacklisted, you are kicked with a message like: 
  "&4&lYou were blacklisted for (TIME) by (STAFF)
  &r&fReason: &r&f(REASON)

&aBeing Blacklisted is a big punishment. You were kicked out of your clan and placed as a spectator for (TIME). You may not chat, break or place, or use any commands."

but for permanent blacklists:

"&4&lYou were permanently blacklisted by (STAFF)
&r&fReason: &r&f(REASON)

&aBeing Blacklisted is a big punishment. You were kicked out of your clan and placed as a spectator for (TIME). You may not chat, break or place, or use any commands."

Being blacklisted replaces the "Revive" clock with a "&cAppeal" Restone Block leading to a appeal website placed in the config. If you try to talk as a blacklisted person, this appears and the message isn't sent: "&4&lYou were permanently blacklisted by (STAFF). You may not talk." for permanent blacklists and "&4&lYou were permanently blacklisted by (STAFF). You may not talk for (REMAINING TIME)." for temp blacklists.

**Hopefully you saw all of this and it gets added! :D _              - w1nst0n**_

**Comment by 1002511** [comment]
The signature got mixed up at the end ;_;

**Comment by RoinujNosde** [comment]
SimpleClans is in maintenance mode.
Suggest it here: https://bukkit.org/forums/plugin-requests.96/

@marcelo-mason
Close.
