### ISSUE TITLE
Clan

### ISSUE THREAD

**Issue by Endergirl2900** [marcelo-mason/SimpleClans#403]
Is it possible to maximize the numbers of clans? as for ex. max 3 clans per world??

**Comment by RoinujNosde** [comment]
It's not possible,
But you could create a plugin to do such thing:
Listen to this event: https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/events/CreateClanEvent.java
Get player's world. Check in config if max clans is reached in this world.
If not, save the new number of clans.
If so, disband the clan.
Just an idea.

@marcelo-mason
I think you can close it.
