### ISSUE TITLE
Everyone can reload without permission

### ISSUE THREAD

**Issue by zlOwnedYou** [marcelo-mason/SimpleClans#407]
Hay I create atm my own server and test all Permissions from the Pluigin and see everyone can reload the pluigin without permissions.
Pls fast help thanks :)

![2016-12-21 1](https://cloud.githubusercontent.com/assets/24700069/21394053/4908fbde-c797-11e6-8615-5c3242b40ffb.png)
![2016-12-21 2](https://cloud.githubusercontent.com/assets/24700069/21394054/491ae272-c797-11e6-82c3-01782d864644.png)
![2016-12-21](https://cloud.githubusercontent.com/assets/24700069/21394055/491cd33e-c797-11e6-9e02-c9644d0ba1dd.png)

**Comment by RoinujNosde** [comment]
Still an issue?

**Comment by RoboMWM** [comment]
Already fixed this a while ago. #387

**Comment by RoinujNosde** [comment]
Thanks.
