### ISSUE TITLE
Could not pass event PlayerCommandPreprocessEvent to SimpleClans v.2.5.3

### ISSUE THREAD

**Issue by zSolitario** [marcelo-mason/SimpleClans#409]
Hi, I would like to know if anyone could help me solve this problem by using the "/." command to talk in the clan chat.

Error: http://i.imgur.com/AmizffZ.png

SimpleClans: 2.5.3
Spigot 1.8.8

**Comment by RoinujNosde** [comment]
Try this [version](http://104.236.246.108:8080/job/SimpleClans/lastBuild/artifact/target/SimpleClans.jar) and let me know ;)
