### ISSUE TITLE
SimpleClans leaders and members no saving?

### ISSUE THREAD

**Issue by zSolitario** [marcelo-mason/SimpleClans#410]
http://i.imgur.com/dxaf6FY.png

I have a problem with clans ... members no saving in list and lose clan

http://i.imgur.com/eIL9onv.png

**Comment by RoinujNosde** [comment]
Still an issue?

**Comment by RoinujNosde** [comment]
@marcelo-mason 
https://github.com/marcelo-mason/SimpleClans/blob/5d8b6d26395fc7a19e414a9a7e4d5b0b4d056052/src/main/java/net/sacredlabyrinth/phaed/simpleclans/managers/StorageManager.java#L658
This line tries to insert player's uuid at the uuid column, but is there such column?
Should it not be created here: https://github.com/marcelo-mason/SimpleClans/blob/5d8b6d26395fc7a19e414a9a7e4d5b0b4d056052/src/main/java/net/sacredlabyrinth/phaed/simpleclans/managers/StorageManager.java#L95 ?

(I'm not on PC, can't test right now. Does this sound like the cause of @zSolitario's problem?)

**Comment by marcelo-mason** [comment]
uuid is added to the table here:  https://github.com/marcelo-mason/SimpleClans/blob/5d8b6d26395fc7a19e414a9a7e4d5b0b4d056052/src/main/java/net/sacredlabyrinth/phaed/simpleclans/managers/StorageManager.java#L831

**Comment by marcelo-mason** [comment]
That updateDatabase method wasn't running in offline mode, this was fixed recently.
