### ISSUE TITLE
Can't invite people to clan?

### ISSUE THREAD

**Issue by MrCrispis** [marcelo-mason/SimpleClans#411]
Hey there, I have all permisions correctly setup, but when I create my clan and I want to invite someone, it says that I don't have the leader permissions.

I have the simpleclans.leader.*, does that permissions exist? Or do I need to add all perms by separate?

(I have OP but still don't work)

**Comment by RoinujNosde** [comment]
Does the issue still occurs to you? What permission plugin do you use (and version?) What server software (and version)? Also, what version of SimpleClans?

**Comment by RoinujNosde** [comment]
Duplicate of #440
