### ISSUE TITLE
Translated language is cropped.

### ISSUE THREAD

**Issue by FlameNeko** [marcelo-mason/SimpleClans#412]
**Good day!**

Straight to the point. I translated this plugin for use in other country, but I've encountered an issue where the chat messages displaying "how-to-use" are cropped. Is there any way to fix this?

**P.S:** Screenshot included.
**P.P.S:** Thank you for your help in advance.

![ykvkde27axg jpg 1097x329 - google chrome 2017-01-28 17 26 34](https://cloud.githubusercontent.com/assets/4739974/22397660/45b1a886-e57f-11e6-873c-e476bef89476.png)

**Comment by MrCrispis** [comment]
try adding it on a extra line underneath.

**Comment by FlameNeko** [comment]
Nope, didn't help.

**Comment by FlameNeko** [comment]
Any other ideas? (Bump)
