### ISSUE TITLE
Config.yml

### ISSUE THREAD

**Issue by FlavioSousa26** [marcelo-mason/SimpleClans#413]
I change the configuration at config.yml and always they reset whats rong?

**Comment by MDelgadoCCM** [comment]
Possibly you are writing invalid yaml, post your new file to an online yaml linter to check if it has errors prior to sabing.

**Comment by FlavioSousa26** [comment]
i can port here?

**Comment by MDelgadoCCM** [comment]
http://yaml-online-parser.appspot.com/

**Comment by FlavioSousa26** [comment]
How i use that?

**Comment by MDelgadoCCM** [comment]
You can use that to check if your config is valid yes.

**Comment by FlavioSousa26** [comment]
copy all paste in that site?

**Comment by MDelgadoCCM** [comment]
After you edit your config, before saving.  Just paste the contents on there, and click Go.  It will tell you if it has errors.

**Comment by FlavioSousa26** [comment]
nothing wrong...

**Comment by MDelgadoCCM** [comment]
Try running the server, it should not get reset.

**Comment by FlavioSousa26** [comment]
It does the same de config reset

**Comment by FlavioSousa26** [comment]
i put for dont verify news clans but always i try do a clan it say "get your clan verified to access advanced features"

**Comment by MDelgadoCCM** [comment]
Could be other plugin interfering, try removing all other plugins temporarily, then seeing if it gets reset then.

**Comment by FlavioSousa26** [comment]
Okay thanks i will try

**Comment by RoinujNosde** [comment]
@FlavioSousa26
Is this still an issue?
