### ISSUE TITLE
Support LuckPerms

### ISSUE THREAD

**Issue by Eufranio** [marcelo-mason/SimpleClans#415]
The permissions are true in LuckPerms, but they're not recognized by SimpleClans, so we aren't able to do stuff.

**Comment by Pawned** [comment]
I've just switched to LuckPerms from PEX, very disappointed to see that the /clan home and /clan home set commands are suggesting users don't have permissions even though they do :(

**Comment by RoinujNosde** [comment]
@marcelo-mason
Could you close it?
