### ISSUE TITLE
Some errors with latest versión

### ISSUE THREAD

**Issue by Zoiter7** [marcelo-mason/SimpleClans#417]
Since version 2.6.0 in spigot 1.8.8 the database (SQLITE and MySql) don't works propertly and also the perms of leader.

**Comment by RoinujNosde** [comment]
Related to #431.
http://104.236.246.108:8080/job/SimpleClans/lastStableBuild/artifact/target/SimpleClans.jar
Try this one.

**Comment by Zoiter7** [comment]
Thanks. I will test it.

**Comment by Zoiter7** [comment]
Now the problem with the database not exist, but the problems with the leader permissions continues
Is the same problem of this issue: https://github.com/marcelo-mason/SimpleClans/issues/440

**Comment by RoinujNosde** [comment]
Duplicate of #440
