### ISSUE TITLE
player locked in /.

### ISSUE THREAD

**Issue by comonier** [marcelo-mason/SimpleClans#419]
when he try use /. join or /. leave commands he just type it on clan channel
command not working.

simpleclans version 2.6.1

**Comment by comonier** [comment]
i have a same version of the plugin [same file] on another server 1.11.2 and ir is working, but in a server 1.8.8 its not working 
its is solved changing   mchat-integration:  (false to true) ? or not ?

**Comment by RoinujNosde** [comment]
@comonier
Try this version: http://104.236.246.108:8080/job/SimpleClans/lastStableBuild/artifact/target/SimpleClans.jar
And let me know.

**Comment by FabioZumbi12** [comment]
Go to player clan file and search for `chat:clanchat`

Remove this from clan on database.

**Comment by comonier** [comment]
solved ty

**Comment by RoinujNosde** [comment]
Thanks for the feedback.
