### ISSUE TITLE
allow PermissionsManager#has to check permissions of a CommandSender breaks /clan lookup and maybe other 

### ISSUE THREAD

**Issue by i9hdkill** [marcelo-mason/SimpleClans#422]
Hey,
these commits:
https://github.com/marcelo-mason/SimpleClans/commit/1e77b25794aeb8f2ef0c994d59929ab160643fbf
https://github.com/marcelo-mason/SimpleClans/commit/5715863b06708c3f696e637147b95847e6d243e8

are breaking /clan lookup xxx 
https://pastebin.com/wK4LCHaK
@RoboMWM

The plugin connnects to Mojang, which isn't a smart way and if he gets null (due to mojang block) he doesn't display anything. Even if Mojang gives an answer, the plugin returns null.

**Comment by marcelo-mason** [comment]
I see.  Can send up a pull request?  I can merge it in.

**Comment by RoboMWM** [comment]
Um, why was I tagged?

**Comment by RoboMWM** [comment]
Huh, for me it's just printing out `null` with no stacktrace - is the stacktrace related?
