### ISSUE TITLE
Gringotts Compatibility 

### ISSUE THREAD

**Issue by Blandroo** [marcelo-mason/SimpleClans#423]
I've tried using Gringotts to create a physical currency (gold ingots) to create a clan it takes the gold ingot out of my inventroy but I believe they're not compatible as when I create a clan the money and gold ingot remains in my account and inventory. If this is something on my end that I need to change please let me know how to fix it but if it's not please update SimpleClans to be compatible with Gringotts. Thanks!

**Comment by RoinujNosde** [comment]
Do you have issues with other plugins as well?
Are you running the latest version of Vault?
