### ISSUE TITLE
1.12 bug list

### ISSUE THREAD

**Issue by Math0424** [marcelo-mason/SimpleClans#425]
no /clan kick or resign its broken
spams people with invites after they have joined
error when joining clan

**Comment by Math0424** [comment]
also can you add an option to make precious stone have a breakable tag, so any player can break or destroy the block?

**Comment by Math0424** [comment]
eta?

**Comment by marcelo-mason** [comment]
This week for sure

**Comment by Math0424** [comment]
any news on the 1.12 bug fixes??

**Comment by RoinujNosde** [comment]
@Math0424
What error do you get on command /clan kick?
And on /clan resign?
Can you give me more details on the invitation problem?
