### ISSUE TITLE
API documentation not up to date.

### ISSUE THREAD

**Issue by ctooley21** [marcelo-mason/SimpleClans#437]
Hello! Trying to create an add on for SimpleClans but the API documentation is not current, as SCCore does not exist as well as ClanPlayerManager that is referenced here https://dev.bukkit.org/projects/simpleclans/pages/api

**Comment by RoinujNosde** [comment]
That page is from an older version, [this one](https://dev.bukkit.org/projects/simpleclans/pages/simple-clans1-api) has a few methods. For all methods, you can check the source code.

**Comment by ctooley21** [comment]
Awesome, thanks!
