### ISSUE TITLE
Leader permissions doesnt work and invite.

### ISSUE THREAD

**Issue by alexms12** [marcelo-mason/SimpleClans#440]
Hi, when i execute some leader command, such as "/clan disband" i get "You do not have leader permission" and same for the invite command, i cant invite any player, i put all nodes to the group:

simpleclans.anyone.*
simpleclans.member.*
simpleclans.leader.*

Last version SimpleClans (http://104.236.246.108:8080/job/SimpleClans/lastStableBuild/artifact/target/SimpleClans.jar)
Spigot 1.8.8
Last version of Vault

Errors: https://pastebin.com/6mENSGrR
My simpleclans config: https://pastebin.com/syHwYYJi

Any help??? Thank you

**Comment by alexms12** [comment]
I use for permissions PermissionsEX 1.23.4.

**Comment by alexms12** [comment]
And i test with OP and say "You do not have leader permission"

**Comment by alexms12** [comment]
Any temporary fix?

**Comment by RoinujNosde** [comment]
I don't know.
Try to edit plugin.yml and change this:
`simpleclans.leader.*:`
`    description: Permissions for those who can be clan leaders`
`    default: false`
`    children:`
Set default as true.

Or try to give this permission: `simpleclans.leader.disband`

I will try to fix it next week.

**Comment by alexms12** [comment]
I will try.

**Comment by marcelo-mason** [comment]
With PermissionsEx your best bet is listing out the permissions rather than using the * groups.  You can find them in the jar (rename to zip and unzip it) inside the config.yml.

**Comment by alexms12** [comment]
Yes.

**Comment by alexms12** [comment]
Dont work.

**Comment by marcelo-mason** [comment]
Are you the leader of the clan you're trying to disband? i.e. with the /clan promote command?

**Comment by alexms12** [comment]
Dont work "You do not have leader permission"

**Comment by alexms12** [comment]
For all leader permissions.

**Comment by marcelo-mason** [comment]
```java
        if (!plugin.getPermissionsManager().has(player, "simpleclans.leader.promote")) {
            ChatBlock.sendMessage(player, ChatColor.RED + plugin.getLang("insufficient.permissions"));
            return;
        }

        ClanPlayer cp = plugin.getClanManager().getClanPlayer(player);

        if (cp == null) {
            ChatBlock.sendMessage(player, ChatColor.RED + plugin.getLang("not.a.member.of.any.clan"));
            return;
        }

        Clan clan = cp.getClan();

        if (!clan.isLeader(player)) {
            ChatBlock.sendMessage(player, ChatColor.RED + plugin.getLang("no.leader.permissions"));
            return;
        }
```

See here's the code a typical command.   The messge you are getting is the one that says "no.leader.permissions".  Its being fired because you are tyring to use commands for a clan while not being the leader of the clan.  Nothign to do with permissions.

**Comment by alexms12** [comment]
But im the leader of the clan.

**Comment by marcelo-mason** [comment]
How do you know?

**Comment by alexms12** [comment]
You can join on my server to test.

**Comment by marcelo-mason** [comment]
sure

**Comment by marcelo-mason** [comment]
Actually, wont help, I wont be able to see your screen.

**Comment by alexms12** [comment]
skype?

**Comment by marcelo-mason** [comment]
Post screenshot of the output of the /clan roster command

**Comment by alexms12** [comment]
wait

**Comment by alexms12** [comment]
http://prntscr.com/g5g6of

**Comment by marcelo-mason** [comment]
What does /clan disband do now?

**Comment by alexms12** [comment]
http://prntscr.com/g5gcze

**Comment by alexms12** [comment]
in my permissionsEX http://prntscr.com/g5gd9a

**Comment by alexms12** [comment]
I get this error too, sorry the spam: https://pastebin.com/QyvtTtjx

**Comment by marcelo-mason** [comment]
I see, thats the key there.  There is somethign wrong with the Sqlite DB.  Looks like the uuid column is not there. hmm.

**Comment by alexms12** [comment]
How i can see this?

**Comment by alexms12** [comment]
Ok

**Comment by alexms12** [comment]
I try disband in console and say that: http://prntscr.com/g5gj9h

**Comment by marcelo-mason** [comment]
Are you running your server in offline mode by any chance?

**Comment by marcelo-mason** [comment]
Download the latest build from my Jenkins.  http://104.236.246.108:8080/job/SimpleClans/

**Comment by alexms12** [comment]
Yes im running in offline mode.

**Comment by alexms12** [comment]
I will test.

**Comment by marcelo-mason** [comment]
Yep then the latest build will fix your problem.

**Comment by alexms12** [comment]
Solved! Thank you so much!

**Comment by marcelo-mason** [comment]
np

**Comment by RoinujNosde** [comment]
The leader permissions problem?

**Comment by alexms12** [comment]
"You do not have leader permission"

**Comment by Zoiter7** [comment]
Also I have the same problem, I try to do all of we commented in this issue and the problem continues

**Comment by RoinujNosde** [comment]
I will look into it tonight (UTC-3).

**Comment by RoinujNosde** [comment]
I have just tested it, with and without Vault, and it worked fine... I can kick, disband, etc.

**Comment by Zoiter7** [comment]
Great, the problem is if you have in config 
online-mode: false
If this in true don't occour the problem.
