### ISSUE TITLE
[Request] Recognize original command plus translated one

### ISSUE THREAD

**Issue by FabioZumbi12** [marcelo-mason/SimpleClans#441]
**/clan reload** shows on help from console but says incorrect command.

**Comment by RoinujNosde** [comment]
Não entendi. Explica com mais detalhes.

**Comment by FabioZumbi12** [comment]
Isso: http://prntscr.com/g6276z

Quando uso só /clan mostra os comandos disponíveis pro console, mas quando uso /clan reload, da que o ocmando esta incorreto.

**Comment by FabioZumbi12** [comment]
Há, achei o prolema! Nos traduzimos os comandos, e traduzimos o reload tbm.

Então fica como sugestão vcs colocarem a tradução do comando como opção, mas o principal ser o traduzido. Tipo eu poder usar `reload` e `recarregar`, e trocar no help tbm.

Abraço.

**Comment by RoinujNosde** [comment]
Já tava escrevendo a solução kkkkk

Vou deixar a sugestão aberta, mas não sei quando implemento.
