### ISSUE TITLE
People can invite the staff with vanish

### ISSUE THREAD

**Issue by Bouger** [marcelo-mason/SimpleClans#448]
If you have a clan and you write "/clan invite" and you press TAB , you can see the names of the staff that are invisibility.

**Comment by RoinujNosde** [comment]
What plugin do you use for invisibility?
Have you tested if this revealing names thing happens to other plugin/plugins? Which one/ones? Do they have this TAB completer feature?

Thanks.

**Comment by Bouger** [comment]
I use Essentials for vanish

**Comment by RoinujNosde** [comment]
> Have you tested if this revealing names thing happens to other plugin/plugins?

**Comment by Bouger** [comment]
Yep, it only happens with simpleclans.

**Comment by RoinujNosde** [comment]
> Which one/ones? Do they have this TAB completer feature?

**Comment by Bouger** [comment]
GIF example: https://gyazo.com/e7a62618ac1bc546f7e40ac94260ae14
When you press "TAB" , you can see all players with vanish.

**Comment by RoinujNosde** [comment]
> Which one/ones? Do they have this TAB completer feature?

Answer this, please.

**Comment by Bouger** [comment]
I don't understand the question, sorry I speak spanish.

**Comment by RoinujNosde** [comment]
You said that you had tested on another plugins.
Which plugins?

Maybe in portuguese:
Você disse que testou em outros plugins. Quais plugins?

**Comment by Bouger** [comment]
I tested only on my own plugin, I can give you the .jar if you need it.

**Comment by RoinujNosde** [comment]
Do you use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/command/TabCompleter.html in your plugin?

**Comment by Bouger** [comment]
No, I don't.

**Comment by RoinujNosde** [comment]
Try reporting it to the Essentials team. It does not seems to be a SimpleClans' issue...
