### ISSUE TITLE
Placeholders not working with PlaceholderAPI

### ISSUE THREAD

**Issue by whoshenry** [marcelo-mason/SimpleClans#452]
I am using Build 45 and the placeholders aren't working with the latest PlaceholderAPI and Spigot 1.12.1.

**Comment by RoinujNosde** [comment]
Hi,
Have you tried contacting PlaceholderAPI's author?

**Comment by whoshenry** [comment]
I have, no response.

**Comment by RoinujNosde** [comment]
Let's wait for his answer. I have no idea how he hooks into SimpleClans...

**Comment by whoshenry** [comment]
I think this is SimpleClan's issue, SimpleClans needs to register on the PlaceholderAPI cloud for the placeholders to work.

**Comment by RoinujNosde** [comment]
Did the author say something is broken on SimpleClans?

**Comment by skilledpt** [comment]
problem is still here

**Comment by RoinujNosde** [comment]
Open an issue here:
https://github.com/Peng1104/PAPI_SimpleClans

This doesn't seem like a SimpleClans' issue.
