### ISSUE TITLE
Console Freeze

### ISSUE THREAD

**Issue by BolsaFamiliaBR** [marcelo-mason/SimpleClans#453]
My console freeze when the DB is loaded  

15.09 19:30:33 [Server] INFO Enabling SimpleClans vLegacy
15.09 19:30:33 [Server] INFO Version Legacy loaded
15.09 19:30:33 [Server] INFO SQLite Connection successful

The console stop work and the server dont start, how can i fix it?

(version of CB: 1.7.2 R.0.3)

**Comment by RoinujNosde** [comment]
More info, dude

**Comment by RoinujNosde** [comment]
You are using the older SimpleClans?

**Comment by BolsaFamiliaBR** [comment]
Yes, i using 2.4.4

**Comment by RoinujNosde** [comment]
Quem vive de passado é museu. Atualiza isso aí. :)

**Comment by BolsaFamiliaBR** [comment]
Coloquei a versão mais atual que tem nos arquivos
https://dev.bukkit.org/projects/simpleclans/files?filter-game-version=

(2.5.3)

Deu a mesma coisa
16.09 15:44:53 [Server] INFO Enabling SimpleClans v2.5.3
16.09 15:44:53 [Server] INFO Version 2.5.3 loaded
16.09 15:44:53 [Server] INFO SQLite Connection successful

Congelou nessa parte novamente

**Comment by RoinujNosde** [comment]
http://104.236.246.108:8080/job/SimpleClans/45/artifact/target/SimpleClans.jar

Esta é a mais recente.

**Comment by BolsaFamiliaBR** [comment]
Agora funcionou, mas quando escrevo algum comando como /clan create, acontece isso

https://pastebin.com/gAZhrQKY

**Comment by RoinujNosde** [comment]
O plugin usa um método das novas versões do Bukkit que não tem na 1.7.2.
Você tem que atualizar o servidor.

**Comment by BolsaFamiliaBR** [comment]
Qual é a versão mais atual que é compatível com essa versão do bukkit?

**Comment by BolsaFamiliaBR** [comment]
Achei uma versão que funcionou perfeitamente (os comandos também :) )

16.09 16:33:42 [Server] INFO BolsaFamiliaBR issued server command: /clan create adm admin
16.09 16:33:43 [Server] INFO [ [ A - Novato III ] BolsaFamiliaBR] * Clan admin created

Obrigado pela ajuda ^^

**Comment by RoinujNosde** [comment]
De nada :)
