### ISSUE TITLE
[request] DiscordSRV API, Allow crews to talk in private to their clan chat over discord.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#457]
The hard works all done:
https://www.spigotmc.org/resources/discordsrv.18494/
DiscordSRV has easy API calls to work with it!
Chatcontrol pro recently integrated with discordSRV, it would be awesome to allow Clans to have their own private discord channel to talk to people in-game, in just their crew! 
The plugin already has a system to authenticate users and link them to their discord accounts and set roles.

Discord allow setting permissions to read/write in channels per person already!

For people like me with 500+ clans, this could really clutter the discord channels (Discord added channel categories) we could make the discord/clan chat temporary if its not used, or have an option in-game to buy it like they do with homes.

**Comment by RoinujNosde** [comment]
Awesome suggestion =D

**Comment by FabioZumbi12** [comment]
A plugin chat, with a channel and a perms to talk in this channels given to the clan is all we need. UltimateChat or DSRV (with user link) can already do this

**Comment by Markusi13** [comment]
Commenting to push the feature request again, is it possible to add this?

**Comment by RoinujNosde** [comment]
> Commenting to push the feature request again, is it possible to add this?

@FabioZumbi12 will be releasing this feature in his UltimateChat plugin

**Comment by FrozenBeard** [comment]
urgh, but we use ChatControl Pro :(

**Comment by RoinujNosde** [comment]
Sounds like a good reason to switch to UChat 😃

**Comment by TomLewis** [comment]
Dousn't have 1/3 of the features I use with ChatControl pro, this is a bummer, I cant switch to it, its too basic.

https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/

**Comment by RoinujNosde** [comment]
I guess using DiscordSRV wouldn't be too much work to implement.
Create this issue in my new repo and I will take a look at it when I have the time.

**Comment by TomLewis** [comment]
You have a new repo? for Simpleclans?

**Comment by RoinujNosde** [comment]
Yeah, you can find it on my user page or on this repo's readme.
