### ISSUE TITLE
Verify command broken.

### ISSUE THREAD

**Issue by PabloMG123** [marcelo-mason/SimpleClans#458]
I have a problem wich is that new players can verify their clans, using the command /clan verify (tag) wich is a mod command that they are not allowed to do. I tried to deny the permission simpleclans.mod.* but it doesnt work, anyone can still verify their clans, even being the lowest rank. I use permissionex for my server.

I suppose i am doing something wrong, can anyone help me?

Im using simpleclans 2.7.5

**Comment by RoinujNosde** [comment]
Paste your config file, please.

**Comment by PabloMG123** [comment]
safe-civilians: false
tag:
  default-color: '8'
  max-length: 5
  bracket:
    color: '0'
    leader-color: e
    left: '['
    right: ']'
  min-length: 2
  separator:
    color: '0'
    leader-color: e
    char: ' '
settings:
  online-mode: true
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  mchat-integration: true
  enable-auto-groups: false
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: en
  disallowed-tag-colors:
  - '4'
  server-name: '&4SimpleClans'
  new-clan-verification-required: true
  allow-regroup-command: true
commands:
  more: more
  ally: ally
  clan: clan
  accept: accept
  deny: deny
  global: global
  clan_chat: .
  force-priority: true
economy:
  creation-price: 100.0
  purchase-clan-create: false
  verification-price: 100,000,000.00
  purchase-clan-verify: true
  invite-price: 20.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
clan:
  homebase-teleport-wait-secs: 5
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 7
  max-length: 100
  max-members: 100
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  ff-on-by-default: false
  min-length: 2
  min-size-to-set-ally: 7
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: e
  separator: '-'
  size: 100
clanchat:
  rank:
    color: e
  tag-based-clan-chat: false
  name-color: e
  player-bracket:
    left: <
    right: '>'
  announcement-color: e
  message-color: b
  tag-bracket:
    color: e
    left: '['
    right: ']'
  enable: true
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
allychat:
  tag-color: b
  name-color: f
  player-bracket:
    left: <
    right: '>'
  message-color: '3'
  tag-bracket:
    color: '8'
    left: '['
    right: ']'
  enable: true
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 30
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
  test: []
  staff: []
  sida: []
  pepi: []
performance:
  use-threads: false
  use-bungeecord: false

**Comment by RoinujNosde** [comment]
Players can verify their own clan or another clan?

**Comment by PabloMG123** [comment]
Players can verify ANY clan.

**Comment by PabloMG123** [comment]
Players can verify any clan they want.

(Edit)

You have any idea what it could be? Because permissions are working fine.

**Comment by RoinujNosde** [comment]
Sorry for the delay, I am gonna take a look at it right now.
