### ISSUE TITLE
Chat Format

### ISSUE THREAD

**Issue by rh-programm** [marcelo-mason/SimpleClans#461]
Can I change the chat format?

**Comment by RoinujNosde** [comment]
clanchat:
    rank.color: e
    tag-based-clan-chat: false
    name-color: e
    player-bracket:
        left: '<'
        right: '>'
    announcement-color: e
    message-color: b
    tag-bracket:
        color: e
        left: '['
        right: ']'
    enable: true

tag:
    default-color: '8'
    max-length: 5
    bracket:
        color: '8'
        leader-color: '4'
        left: ''
        right: ''
    min-length: 2
    separator:
        color: '8'
        leader-color: '4'
        char: ' .'


Search for those settings in config.yml

**Comment by rh-programm** [comment]
thank you
