### ISSUE TITLE
Crackshot guns damage allied clans

### ISSUE THREAD

**Issue by whoshenry** [marcelo-mason/SimpleClans#462]
Can you add support for Crackshot?

Currently, the guns can damage allied clans.

**Comment by RoinujNosde** [comment]
Seems easy to do.

But I will release it as a independent plugin. May you help me test it? If so, what is your email?

**Comment by whoshenry** [comment]
Sure.

henry.daeche@gmail.com

**Comment by whoshenry** [comment]
The plugin you sent works well, thank you so much.

**Comment by RoinujNosde** [comment]
Thanks for testing.
---

If you have the same request: https://www.spigotmc.org/resources/crackshot-simpleclans.48339/
