### ISSUE TITLE
Issue inviting people to clans

### ISSUE THREAD

**Issue by Vengalos** [marcelo-mason/SimpleClans#464]
Everytime I want to invite someone to my clan [I'm the server owner.] it says "The Player doesn't not [doesn't not? Wow.] have the permissions to join clans". I'd have to OP everyone in order to invite them but  you probably understand that I can't do that. Also after I deop them when they're in, they are basically not able to do anything. Is there something I am missing out on? Any help will be appreciated.

**Comment by RoinujNosde** [comment]
What Permissions plugin do you use? Let me see its files. Or at least list the permissions related to SimpleClans that your players own.

**Comment by Vengalos** [comment]
I am using PermissionsEX but do not know how to use it for other plugins.

**Comment by RoinujNosde** [comment]
So you did not give SimpleClans permissions to the players...?

**Comment by Vengalos** [comment]
I took a look into the config.yml file but could not find something that'd help with that.

**Comment by RoinujNosde** [comment]
Read this guide:
https://github.com/PEXPlugins/PermissionsEx/wiki/Basic-Permissions-Setup

I am closing this issue, it does not seem to be a SimpleClans bug. Reopen if you think is necessary.
