### ISSUE TITLE
I figured out how to make a network graph based on SimlpeClans data!

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#465]
My players LOVE visualising data, they were manually spending hours creating crew graphs of how crews were connected, so I decided to learn how to create a network graph from the SimpleClans data and make it into an interactive website! 

The data needed to be manually adapted to get to work with this type of graph, lots of playing around with CSV's, editing in Excel etc to figure it all out, heres the end result;

https://crews.piratemc.com

**Comment by RoinujNosde** [comment]
Cool stuff! 😄
