### ISSUE TITLE
clan.balance not working in language.yml

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#466]
Changed mine to clan.balance: 'Crew-Balance: {0}' 
Does not work, still displays Clan-Balance: {0

**Comment by RoinujNosde** [comment]
Which command do you use?
By the way, does it display "{0}"?

**Comment by FrozenBeard** [comment]
Yeah, it displays the "{0}", I just can't customise the message, I want to change it from Clan to Crew and change the colors, its like the variable name isn't right as nothing changes when I change it.
**/clan bank status** is the command. 
As an addition to this can I suggest an alias?
**/clan bal**, will automatically show the balance of the clan; players are used to /bal from essentials and it trims off needing to write status aswell.

**Comment by RoinujNosde** [comment]
Send me a screenshot of how the clan balance is printed, thanks.

**Comment by FrozenBeard** [comment]
![2017-11-23_16 25 03](https://user-images.githubusercontent.com/144046/33182276-36665b60-d06b-11e7-90f7-df52219c9200.png)

**Comment by RoinujNosde** [comment]
>> As an addition to this can I suggest an alias? /clan bal, will automatically show the balance of the clan; players are used to /bal from essentials and it trims off needing to write status aswell.

You can achieve this by using a Bukkit built-in feature: https://bukkit.gamepedia.com/Commands.yml

**Comment by FrozenBeard** [comment]
@RoinujNosde Yes, I use this greatly, Just thought it would be more tidy.
I will do the alias myself, but for the Editing the crew-balance words, can we get this fixed?

**Comment by RoinujNosde** [comment]
I have fixed it already, just haven't commited the changes :)
