### ISSUE TITLE
Case-sensative chat command!

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#467]
I have my clan chat set to /c but they cant use /C which irritates a lot of people as its case-sensitive.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/listeners/SCPlayerListener.java#L80
equalsIgnoreCase should fix it

**Comment by FrozenBeard** [comment]
No idea what that is, but good news =D
