### ISSUE TITLE
Clan home regroup, sends players to leader!

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#468]
I tested the /clan home regroup today! It has a few issues:

1. It sends the crew to the leader instead of the home.
2. If you have a cost to /clan home, it does not charge anything! if it sends 5 people it should cost 5X what the cost is set at to /clan home! There should also be an option to deduct this cost from the crew balance. If they don't have enough funds they cant regroup the crew.
3. There is no warmup or cooldown, which means they can escape combat INSTANTLY! it needs to have a warmup and cooldown. Bonus points if you work with https://www.spigotmc.org/resources/free-pvpmanager.845/ to see if they are currently PVP tagged.

**Comment by RoinujNosde** [comment]
>> If you have a cost to /clan home, it does not charge anything! if it sends 5 people it should cost 5X what the cost is set at to /clan home! There should also be an option to deduct this cost from the crew balance. If they don't have enough funds they cant regroup the crew.
There is no warmup or cooldown, which means they can escape combat INSTANTLY! it needs to have a warmup and cooldown. Bonus points if you work with https://www.spigotmc.org/resources/free-pvpmanager.845/ to see if they are currently PVP tagged.

I am working on the 1st issue, please create two different issues for the other ones;

**Comment by FrozenBeard** [comment]
Done, split this up to #470 and #471

**Comment by RoinujNosde** [comment]
Thanks.
