### ISSUE TITLE
Clan home regroup > Adding Cost

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#470]
if you have a cost to /clan home, it does not charge anything when using /Clan home regroup! if it sends 5 people it should cost 5X what the cost is set at to /clan home! There should also be an option to deduct this cost from the crew balance. If they don't have enough funds they cant regroup the crew.

**Comment by RoinujNosde** [comment]
>> There should also be an option to deduct this cost from the crew balance.

Only from the clan balance?
What about from the command issuer's balance?

**Comment by FrozenBeard** [comment]
For now, can we have a toggle to select if it comes out the command issuers balance or the clan balance, im not sure what would work better, this will have to be something we use in trial and error. 
Some people may not have or want clan balances, I only turned this on last week after using the plugin years.
