### ISSUE TITLE
Clan home regroup > adding warmups and cooldowns

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#471]
**/Clan home regroup**
There is no warmup or cooldown, which means they can escape combat INSTANTLY! it needs to have a warmup and cooldown. Bonus points if you work with https://www.spigotmc.org/resources/free-pvpmanager.845/ to see if they are currently PVP tagged.

**Comment by RoinujNosde** [comment]
>> Bonus points if you work with https://www.spigotmc.org/resources/free-pvpmanager.845/ to see if they are currently PVP tagged.

Why don't you set this as true:
https://github.com/NoChanceSD/PvPManager/blob/master/PvPManager/src/main/resources/config.yml#L70 ?
