### ISSUE TITLE
Sugestão: /clan investir

### ISSUE THREAD

**Issue by DarkinfBR123** [marcelo-mason/SimpleClans#473]
O **/clan investir** seria um banco inicialmente para o retiro de dinheiro/coins aos administradores. 
O comando poderia ser usado por todos os membro dos clans, onde eles poderiam depositar uma certa quantidade usando **/clan investir <valor>** e os administradores poderiam usar o comando **/clan money <quantidade do valor>**(lembrando que os próprios administradores podem adicionar).  O dinheiro iria ficar na conta do clan, onde o administrador pode usar o comando para investir seja em pvp, base e projetos.
 E existiria o /clan top money. Onde seria possível ver os top clans com mais alta quantidade depositada e algumas informações dos clans como:
-> Nome do clan
-> Dono(s)
-> Valor
-> Membros
-> KDR.
Um exemplo seria::
========================
(ZDN) Zombies da Noite
Donos: DarkingBR123 , NewsenseiXD
Banco: Z$ 1.000,43
KDR: 1.3
========================
Isso faria uma competição entre os players para sempre serem o clan top, seja por kdr e money.

**Comment by RoinujNosde** [comment]
Você já conhece o comando /clan bank deposit?
