### ISSUE TITLE
Tag de chat

### ISSUE THREAD

**Issue by Thi4goDxD** [marcelo-mason/SimpleClans#477]
por favor me ajuda , quando aparece a tag de clan no chat o meu nik todo fica dar cor seteda como padrao , mesmo usando o /nick pra deixar colorido nao muda , preciso que mude issu algume ajuda????

**Comment by Thi4goDxD** [comment]
help

**Comment by RoinujNosde** [comment]
Está usando qual versão?

**Comment by Thi4goDxD** [comment]
Legacy 2.4.4

Em 25 de dez de 2017 6:09 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by Thi4goDxD** [comment]
Eu preciso colocar a TAG assin [L] tagdoclan groupprefix Nick : mensagen,
eu utilizo o legend chat e group manager

Em 25 de dez de 2017 6:35 PM, thiagocraft3@gmail.com escreveu:

**Comment by RoinujNosde** [comment]
Essa versão é muita antiga. Não poderei te ajudar.
Se quiser baixar a mais nova:
http://104.236.246.108:8080/job/SimpleClans/lastSuccessfulBuild/artifact/target/SimpleClans.jar

**Comment by Thi4goDxD** [comment]
mais ela funciona no 1.5.2?


2017-12-25 18:48 GMT-02:00 Edson Passos <notifications@github.com>:

**Comment by Thi4goDxD** [comment]
http://prntscr.com/hs6p6k Prefix vip
http://prntscr.com/hs6pfo Legend chat config minha
http://prntscr.com/hs6pnv config do simpleclans
http://prntscr.com/hs6q2t como quero que seja


2017-12-25 18:49 GMT-02:00 Thiago Felizardo <thiagocraft3@gmail.com>:

**Comment by RoinujNosde** [comment]
Como está ficando no chat?

**Comment by Thi4goDxD** [comment]
Esta ficando tipo [L] [Moderador] [clan] Nick : mensagem

Em 25 de dez de 2017 7:04 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by Thi4goDxD** [comment]
Só que tem um problemão , tipo depois que termina a TAG vem o Nick mais a
cor dos dois se junta e tipo se a cor padrão da TAG clan for 8 , a tag e o
Nick fica da cor 8

Em 25 de dez de 2017 8:18 PM, "Thiago Felizardo" <thiagocraft3@gmail.com>
escreveu:

**Comment by Thi4goDxD** [comment]
E tento usar o comando /Nick mais mesmo assim a cor fica a mesmo e não sai

Em 25 de dez de 2017 8:20 PM, thiagocraft3@gmail.com escreveu:

**Comment by RoinujNosde** [comment]
Tente colocar display-chat-tags como false

**Comment by Thi4goDxD** [comment]
Mais aí iria sair a TAG ,não iria?

Em 25 de dez de 2017 8:21 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by RoinujNosde** [comment]
Se desativar aquilo o SimpleClans para de mostrar a tag. Aí o legendchat entra em cena, ele consegue pegar a tag do clã sem aquela opção.

**Comment by Thi4goDxD** [comment]
A nossa disso eu não sabia , quando eu for lá no pc vou tentar essa
alternativa , mais qual formato eu coloco no legend chat pra ler a TAG de
clan?

Em 25 de dez de 2017 8:49 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by Thi4goDxD** [comment]
Tipo o {clan} na ta tanto certo


Em 25 de dez de 2017 8:54 PM, "Thiago Felizardo" <thiagocraft3@gmail.com>
escreveu:

**Comment by RoinujNosde** [comment]
{bprefix}

**Comment by Thi4goDxD** [comment]
Daí ela pega a TAG do simoleclans?

Em 25 de dez de 2017 8:58 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by Thi4goDxD** [comment]
Simpleclans*

Em 25 de dez de 2017 9:03 PM, "Thiago Felizardo" <thiagocraft3@gmail.com>
escreveu:

**Comment by RoinujNosde** [comment]
Sim.

**Comment by Thi4goDxD** [comment]
olha amigo
http://prntscr.com/hs8j4g
http://prntscr.com/hs8jh7
nao apareceu nem tag agora


2017-12-25 21:08 GMT-02:00 Edson Passos <notifications@github.com>:

**Comment by Thi4goDxD** [comment]
o meu server ja esta praticamento pronto , so colocar host e abrir , mais o
unico problema e essa da tag


2017-12-25 21:58 GMT-02:00 Thiago Felizardo <thiagocraft3@gmail.com>:

**Comment by RoinujNosde** [comment]
Use-async-chat-event
Marque como true no legendchat

**Comment by Thi4goDxD** [comment]
Cara até agora não deu nada , quando eu liguei o async , eu entrei no serve
e estava tipo [L] Thi4go_DxD , tipo tinha desaparecido a TAG vip e a cor do
meu nick

Em 25 de dez de 2017 10:09 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by RoinujNosde** [comment]
Tente pedir ajuda ao desenvolvedor do LegendChat.
Isso não é um bug do SimpleClans...

**Comment by Thi4goDxD** [comment]
Eu já encontrei um fórum deles que explica bem , obrigado por toda a ajuda

Em 26 de dez de 2017 11:14 AM, "Edson Passos" <notifications@github.com>
escreveu:

Tente pedir ajuda ao desenvolvedor do LegendChat.
Isso não é um bug do SimpleClans...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/marcelo-mason/SimpleClans/issues/477#issuecomment-353967614>,
or mute the thread

**Comment by RoinujNosde** [comment]
Sem problemas

**Comment by Thi4goDxD** [comment]
Só uma última dúvida , como faço pra traduzir o simpleclans? Pra pt br

Em 26 de dez de 2017 11:36 AM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by RoinujNosde** [comment]
Nunca usei esta versão antiga, mas se for parecida com a nova, tem um arquivo "language.yml".

**Comment by Thi4goDxD** [comment]
Não estou mais usando a antiga , a que estou tem um arquivo chamado
simpleclans

Em 26 de dez de 2017 11:45 AM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by Thi4goDxD** [comment]
E outro config,
Quando abro o arquivo simpleclan tem um monte de bolinha Pretas é algumas
letra
Uso notepad++

Em 26 de dez de 2017 11:45 AM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by RoinujNosde** [comment]
O arquivo language deve estar dentro do .jar

**Comment by Thi4goDxD** [comment]
Blz , agora sim , já não tenho mais duvidas , brigadão , flw

Em 26 de dez de 2017 11:50 AM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by RoinujNosde** [comment]
De nada

**Comment by Thi4goDxD** [comment]
ola eu novamente ksksk , agora consegui colocar a tag do clan , mais ja tem
outro problema , a tag so fica no chat que defino como defaut , eu falo
normal no chat aparece ,dai falo no /g e nao aparece
olha esse e do /g
http://prntscr.com/hsoaam
esse do chat normal /l
http://prntscr.com/hsoah5

2017-12-26 11:54 GMT-02:00 Edson Passos <notifications@github.com>:

**Comment by Thi4goDxD** [comment]
se puder ersponder o quanto antes , ja estou perdeno muito tempo pra
configurar o simpleclans , ja estou a a 4 dias so nesse plugins
tenho que terminar as warps do meu srrver ainda


2017-12-26 22:17 GMT-02:00 Thiago Felizardo <thiagocraft3@gmail.com>:

**Comment by RoinujNosde** [comment]
Como tá a configuração do /g e do /l?
Isto é, os arquivos dos canais.

**Comment by Thi4goDxD** [comment]
g http://prntscr.com/hsv5hr
l http://prntscr.com/hsv5nz
config legend chat
http://prntscr.com/hsv5yc

2017-12-27 9:23 GMT-02:00 Edson Passos <notifications@github.com>:

**Comment by Thi4goDxD** [comment]
e qual versao do simpleclans ja vem com a opçao de linguagem br?


2017-12-27 10:20 GMT-02:00 Thiago Felizardo <thiagocraft3@gmail.com>:

**Comment by RoinujNosde** [comment]
Não faço ideia de por que está sem tag no /g

> e qual versao do simpleclans ja vem com a opçao de linguagem br?

A última, mas a tradução não está completa.

**Comment by Thi4goDxD** [comment]
pronto ja consegui a tag , mais agora tem um problema dentro do plugin
quando digito /clan list , aparece o nome do meu clan assim
"nullnullTBMnullnull"
o que faço?

Em 27 de dezembro de 2017 10:52, Edson Passos <notifications@github.com>
escreveu:

**Comment by RoinujNosde** [comment]
Qual versão do plugin?

**Comment by Thi4goDxD** [comment]
Que tá com #59 do seu site da Jenkins


Em 27 de dez de 2017 10:38 PM, "Edson Passos" <notifications@github.com>
escreveu:

**Comment by Thi4goDxD** [comment]
E que eu escolhi a que dizia que tinha melhorado o chat e ela funcionou no
meu Bukkit 1.5.2

Em 28 de dez de 2017 8:30 AM, thiagocraft3@gmail.com escreveu:

**Comment by RoinujNosde** [comment]
http://104.236.246.108:8080/job/SimpleClans/lastSuccessfulBuild/artifact/target/SimpleClans.jar
Baixe esta
