### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by Rocologo** [marcelo-mason/SimpleClans#481]
I get this bug in the console

 ERROR Query: UPDATE `sc_players` SET `name` = 'jehako' WHERE uuid = '850c7057-05b9-4562-9f67-834ad7e6260c'; 20.01 12:03:10 [Server] ERROR Error at SQL UPDATE Query: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 59,028,486 milliseconds ago. The last packet sent successfully to the server was 59,028,486 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

Im a dev my self and I know what this means. You need to close ALL connections to the database, if you dont do this the MySQL server will drop the connection after some time. And then you get this error.

So after doing the query / update, close the connection.

**Comment by RoinujNosde** [comment]
What version are you using?

**Comment by Rocologo** [comment]
Sorry, you need of cause that
V 2.7.10
build 68
Downloaded from tour jenkins server
