### ISSUE TITLE
Error using some commands

### ISSUE THREAD

**Issue by M1SM4TCH** [marcelo-mason/SimpleClans#482]
When I use /clan doesn't show anything ingame and shows that on console: https://hastebin.com/osokupexag.vbs

And when a player uses the demote command (and the config is confirmation-for-demote: true) causes a huge flood for the clan.

Using PaperSpigot 1.8.8 and SimpleClans b73 (from Jenkins)

**Comment by RoinujNosde** [comment]
* /clan
Delete your language file and let it regenerate. A line is missing. (Backup it if you have made changes)

* demote
Flood on bb or console?

**Comment by M1SM4TCH** [comment]
/clan ok

Flood on bb, all members off the clan receive the message, multiple times per minute.
