### ISSUE TITLE
Player deaths cause extreme lag

### ISSUE THREAD

**Issue by TrademarkTM** [marcelo-mason/SimpleClans#484]
Hey!
I am having this insanely annoying problem with SimpleClans, when a player dies the server freezes to 2 seconds, the next ones are normal, but after something like 2 minutes it happens again.

Timings after freeze: https://timings.spigotmc.org/?url=nekuqebaxa
Configuration: https://hastebin.com/ikudofaxej.cs

Database, if needed:
[SimpleClans.zip](https://github.com/marcelo-mason/SimpleClans/files/1741762/SimpleClans.zip)

I'm also using:
- custom language file
- DeathMessagesPrime
- CombatLogX
- SimpleClans placeholders in scoreboard

Hope this can be fixed!
Thanks!

**Comment by RoinujNosde** [comment]
Can you post again your config, please? The link expired.
