### ISSUE TITLE
Cross server SimpleClans

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#488]
Hey!
How safe is it to use SimpleClans Cross server via MySQL?

I've only used it on my Survival, but i'm expanding into mini games that I want to include SimpleClans integration with existing clans without them having to re-create their Clan.

Now im sure just using the same MySQL details on my second or third servers would pull the information perfectly fine, Im just worried about data getting messed up between servers saving data. If somone is doing something to do with the crew on one server and then someone on the other server is doing crew related things on another, could data get messed up?

**Comment by RoinujNosde** [comment]
I think this could happen:
Ex.: I join clan "A" on server "1", logout and then join clan "B" on server "2".

There could be problems with the balance also.
