### ISSUE TITLE
Homeiswheretheheartis

### ISSUE THREAD

**Issue by Resoluciones** [marcelo-mason/SimpleClans#490]
Hi!

Do you think it would be possible to make SC hook into [Homeiswheretheheartis ](https://dev.bukkit.org/projects/homeiswheretheheartis)protection?

Thanks!!!

**Comment by RoinujNosde** [comment]
How would this hook work?

**Comment by Resoluciones** [comment]
> 
> 
> How would this hook work?

Hi!  It would hook with a similar system than PreciousStones; land would be protected for clan users.

**Comment by FrozenBeard** [comment]
there is no way this needs to be integrated lol

**Comment by Resoluciones** [comment]
I see!  Thank you for your clarification!
