### ISSUE TITLE
Vitals command error

### ISSUE THREAD

**Issue by Lurreisper** [marcelo-mason/SimpleClans#492]
Hello, I'm with this error in "/clan vitals" command.

https://hastebin.com/imerugeyaw.vbs

**Comment by RoinujNosde** [comment]
The link you shared is "empty".

**Comment by Lurreisper** [comment]
https://pastebin.com/NRH3D1rD

**Comment by Lurreisper** [comment]
You mean 1.13? My server is 1.8, I can test it, but it will be useless for me :c

**Comment by RoinujNosde** [comment]
> You mean 1.13?

Yes.

**Comment by Lurreisper** [comment]
Oh :/ I'll disable this command, I don't use 1.13, sorry
