### ISSUE TITLE
simpleclans.member.ally does not work.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#498]
Trying to denote this permission from a second world, but it does nothing if you allow it or deny it.

**Comment by RoinujNosde** [comment]
What do you mean by "denote"?
(I'm not a native speaker)

**Comment by RoinujNosde** [comment]
I see.
So, members with this permission denied are still able to use the chat?

**Comment by FrozenBeard** [comment]
Yup, thats right! 
Basically I have a "punihsment" world, where I don't want them to talk at all, in global chat or ally/crew chat, I think the crew chat permission is the same, so im trying to deny them the use, so when there in a punishment they cant talk!

**Comment by RoinujNosde** [comment]
What permissions plugin do you use?

**Comment by FrozenBeard** [comment]
Luckperms sorry I must have missed this reply!
