### ISSUE TITLE
clan lookup, past clans

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#502]
/clan lookup username, has a past clans area, but its never worked. Was this a feature that never got finished?

**Comment by RoinujNosde** [comment]
Take a screenshot of the output, please.

**Comment by FrozenBeard** [comment]
![](https://i.imgur.com/4be6ET2.png)

**Comment by RoinujNosde** [comment]
Thanks.
Are you sure this player was part of another clan?
I remember from my time as a player that this feature used to work... maybe it broke.

**Comment by FrozenBeard** [comment]
Yup, he's 100% been in multiple clans

**Comment by RoinujNosde** [comment]
Thanks for the feedback, it will be fixed in the next commit.
