### ISSUE TITLE
Clanff block not work

### ISSUE THREAD

**Issue by Doritoz** [marcelo-mason/SimpleClans#506]
Hello, I'm sorry to ask for this but I need a lot, I have a 1.7.10 thermos server (forge + bukkit) and clan members blocking damage does not work (clan clanff block) with some mod weapons I use, pvp protections in the world guard work with them but no simple clans, would you help me?

**Comment by RoinujNosde** [comment]
Ask the developer of this weapons plugin to fire the EntityDamage event.
