### ISSUE TITLE
Jenkins and Maven are Down

### ISSUE THREAD

**Issue by kluberge** [marcelo-mason/SimpleClans#507]
Cannot connect to the IP hosting the Jenkins/Maven repo via HTTP GET.

**Comment by FrozenBeard** [comment]
Bump @RoinujNosde

**Comment by RoinujNosde** [comment]
Nothing I can do about it, but I've released an update: https://github.com/marcelo-mason/SimpleClans/releases

**Comment by FrozenBeard** [comment]
@RoinujNosde Thank you, can you update the Spigot page too with a download link? the link on the Spigot page is broken causing bad reviews. All the images are broken on the Bukkit/Spigot page too, can we re-host them on imgur and get them fixed.

**Comment by RoinujNosde** [comment]
@FrozenBeard only the author can.

**Comment by RoinujNosde** [comment]
@marcelo-mason
Can you update the download link on spigot/bukkit to https://github.com/marcelo-mason/SimpleClans/releases/latest ?
