### ISSUE TITLE
/c join shows up in discord SRV global

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#513]
Ahoy!
Bit of a random bug here, I use discord SRV to have global chat sent to a discord channel, sometimes when people /c join to join their crew chat (I changed the commands) their chat then goes to the discord SRV global channel too.

**Comment by RoinujNosde** [comment]
Isn't there a way on DiscordSRV to filter some messages out?

**Comment by FrozenBeard** [comment]
I hope so, Its weird, its because I think its a toggle, when you /c join, you then write in chat normally, so im guessing it thinks its in global chat? Ill see if I can filter by prefix in DiscordSRV.

**Comment by RoinujNosde** [comment]
If there isn't such feature, suggest it to the developer.
