### ISSUE TITLE
Request: Admin command to demote crew leaders

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#517]
We have 866 crews with 6,342 crew players over 5+ years of use.
We have a lot of very old crews with players that no longer play and the 50% of leaders online to kick out a leader is proving difficulty to the large crews with inactive/banned Crew leaders as they cant get enough Crew leaders online at the same time with timezones/there just isnt enough of them vs the inactive leaders.
Can we please get an admin command to demote a leader in a crew? They could then just post on our forums/discord for their crew leaders to be removed and admins can decide.

I don't think having a "supreme leader" to overrule a crew would be a resolve as some players have suggested to me haha

Another quick option, could we get a parameter in the settings file to set the percentage needed of leaders online to vote on a crew leader getting kicked?

**Comment by RoinujNosde** [comment]
> Another quick option, could we get a parameter in the settings file to set the percentage needed of leaders online to vote on a crew leader getting kicked?

Forgot about this one
