### ISSUE TITLE
Request: Update for Dynmap Simpleclans

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#518]
https://dev.bukkit.org/projects/dynmap-simpleclans

Can this please be updated & moved to spigot too.

I just want to show clan homes on the live map as its own layer on the map.

**Comment by RoinujNosde** [comment]
What happens if you try to use it?

**Comment by RoinujNosde** [comment]
![Captura de tela de 2019-08-11 10-57-15](https://user-images.githubusercontent.com/6441328/62834737-e0ee3f00-bc26-11e9-972d-84990564a328.png)

**Comment by RoinujNosde** [comment]
https://github.com/RoinujNosde/Dynmap-SimpleClans/releases

Test it, please.
