### ISSUE TITLE
MySQL and tags

### ISSUE THREAD

**Issue by YuriNMDS** [marcelo-mason/SimpleClans#523]
??? Sorry i really don't know what do, but when i enable MySQL, the tags don't stay enabled

**Comment by RoinujNosde** [comment]
What tags are you talking about?
What version are you using?
(Você fala português?)

**Comment by YuriNMDS** [comment]
Opa, falo sim, estou falando das tags do chat, e uma pergunta, você teria o simpleclans já traduzido em português?
![image](https://user-images.githubusercontent.com/46354887/62569971-9c992280-b865-11e9-9760-720d55a5a358.png)

**Comment by RoinujNosde** [comment]
Tem um arquivo language em português dentro do jar, ele não está 100% traduzido.
Quando trocou para MySQL, vc criou novamente o clã?

**Comment by YuriNMDS** [comment]
Não criei não, eu utilizei um programa para converter

**Comment by RoinujNosde** [comment]
O resto está funcionando?
O que acontece se você digita /clan roster?

**Comment by YuriNMDS** [comment]
Olha eu conseguir resolver, mas eu realmente não entendo o por quê, mas quando tu desativa o "online-mode" simplesmente as tags somem

**Comment by RoinujNosde** [comment]
Quando o online-mode da config tá false, o plugin salva os players por nome, se eu não me engano.
Então se o seu banco de dados tava UUID, o plugin provavelmente estava achando que os uuids eram nomes.

Que bom que resolveu.
