### ISSUE TITLE
Upkeep tax

### ISSUE THREAD

**Issue by RoinujNosde** [marcelo-mason/SimpleClans#524]
maybe also make it possible to add upkeep to the clan. So that you pay a certain amount every day to keep the clan. maybe even make it possible categorize clans into size. For instance a clan with 1-10 members pay 10 coins, a clan with 10-20 pay 30 and so on.

_Originally posted by @erik1988 in https://github.com/marcelo-mason/SimpleClans/issues/254#issuecomment-113879225_

**Comment by RoinujNosde** [comment]
Send a warning message, if the clan doesn't have enough to pay, to the BB hours before collecting the tax.

**Comment by FrozenBeard** [comment]
can we please get this as a toggle only IF the crew has a fee?
So then crews without a fee do not need to pay upkeep, but a crew that does tax its player has to pay their own tax?
