### ISSUE TITLE
Add new optons to the "commands" menu when you use an empty /clan

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#526]
All the new features like fees, demoting clan members for admins etc all need to be added to the help menu of commands when someone uses /clan with no parameters to list what they can do.
**Edit:** Just realized I haven't set the permissions yet.. (this could be why)

Can we get the Wiki updated here with all commands and permissions, im sifting through the code to figure out permissions atm.

**Comment by RoinujNosde** [comment]
> Just realized I haven't set the permissions yet.. (this could be why)

That could make the fee command show up, but I think I forgot to add the demote command to the menu

> Can we get the Wiki updated here with all commands and permissions, im sifting through the code to figure out permissions atm.

Yes
