### ISSUE TITLE
Request: With the fee introduction, can inactive-player-data-days send a BB message & purge banned

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#528]
With the introduction of fees for clans, with having crews for over 5 years, we have crews with 100's of people, some banned, some inactive, could we get a bb message when someone is purged from a clan? then people know its happened. 

is it possible to purge banned players? I use BanManager as my ban system, sadly I dont think it updates the default banned-players.json.
We could have a new variable 
```
purge:
  banned-player-data-days: 30
```
So if they have been banned for 30 days they are purged from the crew.

Thanks!

**Comment by RoinujNosde** [comment]
I could create a purge command and then you could make BanManager run the command.

**Comment by FrozenBeard** [comment]
That'll be a simple way to do it!
