### ISSUE TITLE
Fee on profile + message on wrong value

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#529]
Ive searched the code and I cant find a way to enable to crew fee, they can set it with `/crew fee set 5`, it saves this in the database and gives them the message its set and sets a bb message, but when you `/crew fee check` its saying its Disabled but the fee number is set. I looked in the database and I can see that fee_enabled is 0 for the crew, are fees automatically enabled if its not 0? or is there a command to enable/disable? I cant figure it out.
 
- Players can use words in `/crew fee set imaword` and it resets to 0 which is good, but it does not give them an error that its not a double number
- Crew fees are not shown on `/crew profile crewname` (Be public so that people can decide if they want to join a crew)

**Comment by RoinujNosde** [comment]
To enable, you use /clan toggle fee (https://github.com/marcelo-mason/SimpleClans/wiki/Member-Fee).

**Comment by FrozenBeard** [comment]
Brilliant that toggle worked, I just noticed its actually in the /crew when you don't put a variable, no idea how I missed it. Thanks.
If I come across any other weird behavior I will post in here too.

**Comment by RoinujNosde** [comment]
Thanks for the feedback
