### ISSUE TITLE
[Dynmap-SimpleClans] Crew homes display, but it broke players showing on the live map.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#531]
https://map.piratemc.com/

Crew homes are being displayed now in their own layer which is good, but its stopped all players from showing on the live map, I have specific settings for people showing in certain light levels.
This is my dynmap config: https://gist.github.com/FrozenBeard/8916c52e2346fe97de77e6a3fa1888de

Is this plugin changing the light level for players or something? 

Turns out there is not an issues section on the Dynmap-SimpleClans repo, so im posting here

**Comment by FrozenBeard** [comment]
Wrong damn repo.

**Comment by RoinujNosde** [comment]
The plugin is hiding the players by default. They can toggle it using /map toggle.

(You can open the issue on the other repo now)

**Comment by FrozenBeard** [comment]
Moved to https://github.com/RoinujNosde/Dynmap-SimpleClans/issues/3
