### ISSUE TITLE
[Dynmap-SimpleClans] Customising the logo

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#532]
Can I set the default logo for Clan homes? my server re-branded clan to crew, so Clan is the wrong word for us, I see that its in /standalone/markers.php?marker=_markers_/simpleclans.home.png
But replacing this doesn't seem to work properly.

Could we please have the icon moved to an icons directory in the plugin folder, and a config option for default icon?

It would also be nice if the crews could pick from a list of pre-determined Icons that I upload to this icons directory, so they can slightly customize their crew icon, I was going to make 1 icon in all of the minecraft colors so they can have a custom color for their icon.

**Comment by RoinujNosde** [comment]
Until I implement this, change the icon inside the jar.

(https://github.com/RoinujNosde/Dynmap-SimpleClans/issues)

**Comment by FrozenBeard** [comment]
Moved to https://github.com/RoinujNosde/Dynmap-SimpleClans/issues/1
