### ISSUE TITLE
[Dynmap-SimpleClans] layer.homes.format add more crew placeholders.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#533]
Requesting, can we please get more crew placeholders for the formatting of the crew homes shwoing when you hover over, some crews do not set names just their tag, so when you hover over some they just show (home) and nothing else, I would like to at the least display their tag aswell so that we know whos home it is.
other helpful tags could include member count etc.

**Comment by RoinujNosde** [comment]
https://github.com/RoinujNosde/Dynmap-SimpleClans/issues

**Comment by FrozenBeard** [comment]
Moved to https://github.com/RoinujNosde/Dynmap-SimpleClans/issues/2
