### ISSUE TITLE
How do I use the rank commands?

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#536]
When you put up https://github.com/marcelo-mason/SimpleClans/wiki/Permissions
I noticed Ive only been using /crew setrank this entire time, looking at the perms, I see Assign, create, delete, detail and list, but I cant seem to find the command to use these, I have assigned the permissions and no extra commands are showing in /crew, I see on the old bukkit page its /rank which is weird, I would assume it was /crew rank create &c&lRank Name

Am I not understanding this correctly? or is this old legacy replaced by setrank?
```
- simpleclans.leader.rank.assign:
- simpleclans.leader.rank.create:
- simpleclans.leader.rank.delete:
- simpleclans.leader.rank.detail:
- simpleclans.leader.rank.list:
```

**Comment by RoinujNosde** [comment]
I don't think these commands were implemented. There is no code for them, only setRank.

**Comment by FrozenBeard** [comment]
That explains why I cant get these permissions to work then! ok, thanks, Ill remove them.
