### ISSUE TITLE
Request: Clan descriptions. - Allow clan leaders to write a brief description about their crew

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#537]
Allow clan leaders to write a brief limited description about their crew to show up in /clan profile, so they can explain what their goal is.

**Comment by RoinujNosde** [comment]
How brief?

**Comment by FrozenBeard** [comment]
Most likely the same as Twitter, so about 280 or 140? are you thinking database scheme limits or displaying in game. Would be good as a config option as it will need testing to see how players react to having this, there's bound to be some way some player abuses it.
The reason I ask is because some crews want to show there a building crew, some want to shot there a PVP crew, some want to have a message saying they are recruiting etc, so many variables, I thought a description would cover as many things as possible, some crews have their name as the description, which isn't the best option at present. 
 
Then again depends how it would show in the profile, a lot of our crews are very packed already!

![2019-08-25_16 33 47](https://user-images.githubusercontent.com/144046/63652533-509d1780-c759-11e9-90e1-e0b846b38699.png)

would we put it directly under their Name:?

**Comment by RoinujNosde** [comment]
I was thinking about database limits. I will set it as 255, but add a config to decrease it.

> would we put it directly under their Name:?

I think it's the best place
