### ISSUE TITLE
2.7.23 Fully errors out and breaks plugin.

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#542]
CTRL+F simpleclans showed me 13,000 mentions of SimpleClans, I assume its trying to iterate through a task for every single crew, nobody is shown as in a crew now.
Moved from 2.7.22 to 2.7.23 on paper 1.12.2.

https://gist.githubusercontent.com/FrozenBeard/04438dc37f2cc27c8914323bfb137a77/raw/01e054aa1941e128785e94195719ed900decf375/latest.log

**Comment by RoinujNosde** [comment]
Is this your complete log?
This error shouldn't break the plugin, it's just a debug message (that I realize now I should've ignored).
Try to look for something like: "Error occurred while enabling"

**Comment by FrozenBeard** [comment]
Sorry "fully broken" as in nobody was in crews, none of the features worked etc.

**Comment by RoinujNosde** [comment]
Did you find a different error?

> What version of GP did you test against? 1.12.2 can only use up to 16.8.

I don't think GP is the cause, SimpleClans doesn't depend on it.

**Comment by FrozenBeard** [comment]
Nope I didn't find any more error's, I can  try a debug version locally of that helps?

**Comment by RoinujNosde** [comment]
You say none of the features were working. What do you mean? What happens if you use the /clan list?

**Comment by RoinujNosde** [comment]
Run this SQL query `UPDATE sc_players SET resign_times = "{}";`

**Comment by FrozenBeard** [comment]
Ok done, shall I use 2.7.25, or will that not work on 1.12.2?
