### ISSUE TITLE
Suggestion: ranks with permissions

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#544]
I had a recent request from players to add a new role to crews:
untrusted, trusted, **mod**, leader.
Mod may no be the correct title, but leader is like an admin and mod is in between trusted and leader, their main request was so they could invite more people to the crew when their leaders are offline.

So i'm thinking the best way to solve this issue is a system to allow leaders to invite offline players, without creating a new rank, as the only real thing they wanted was for this rank to be able to invite more players but not kick them.

Alternative idea 2: Their in-game ranks they can set, if we made these ranks they can save/set then each rank could have a permission attached to do tasks in the crew, like invite.

**Comment by RoinujNosde** [comment]
I like this in-game rank idea.
There could be permissions to regroup, invite, kick, etc.

Self-note: does the rank stays if the player is kicked/resigns?

**Comment by FrozenBeard** [comment]
I touched on this briefly before when I found the permissions #536 but no code to go with it lol 
I would kick them if they are kicked/resign yes!

So the crew leaders would end up being able to create these ranks, assign them, set perms to them (like just invite etc) list them, delete them (People reset to blank/trusted).

This would also open up a lot more ideas later for working with other plugins if these are permission based.

Would be quite cool for when they list ranks in their crew and then click them to list players with those ranks. They could be ordered auto based on the amount of permissions they have (More perms = higher rank) so then they dont have to bother setting weight.

At present when you hover over usernames in my chat, their Cutom crew rank is displayed using either placeholderapi or a placeholder directly from SimlpeClans, so we would need to make sure the placeholders dont break too!

**Comment by RoinujNosde** [comment]
Messages:
"You're not in a rank"
"Your rank does not have permission to do this"

Todo:
Remove player from rank after leaving the clan/ clan getting disbanded.

**Comment by RoinujNosde** [comment]
> (People reset to blank/trusted).

I was thinking of getting rid of the trusted thing. If they want, clan leaders could create a rank to replace it. They would have more freedom to customize.
Ex.: A rank could have permission to view the vitals, but not visit the clan home.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/wiki/Ranks-with-permissions

**Comment by FrozenBeard** [comment]
Top man! I just need to get myself on 1.13 now :(

**Comment by RoinujNosde** [comment]
@FrozenBeard check out the latest release! ;)

**Comment by FrozenBeard** [comment]
@RoinujNosde oh awesome! It looks like its just source code, is there a compiled jar somewhere?

**Comment by RoinujNosde** [comment]
@FrozenBeard https://www.spigotmc.org/resources/simpleclans.71242/
