### ISSUE TITLE
Bug: Simpleclans startup error & formatting issue

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#545]
Totally missed this error as its all on one line and didnt wrap, so i'm not sure when this started to happen:

https://gist.github.com/FrozenBeard/f6109d20dd4ad3f7cb845f6a64bb3437

![2019-09-18_16 53 31](https://user-images.githubusercontent.com/144046/65242751-be312f00-dade-11e9-9686-e527e237b69b.png)

**Comment by RoinujNosde** [comment]
Startup error? Send me the error log.

What args did you use on the list command?
