### ISSUE TITLE
Residence support

### ISSUE THREAD

**Issue by kroko1992** [marcelo-mason/SimpleClans#547]
would it be possible to get the same support for Residence as GriefPrevention do?

Residence: https://www.spigotmc.org/resources/residence-1-7-10-up-to-1-14.11480/

also as a side note, do anyone know if its possible to remove the automatic clan removal? i am going to get a website system that displays all clans and i wants all clans to be there forever

**Comment by RoinujNosde** [comment]
Change `enable-auto-groups` to `true`.
And use `/res gset <residence> clan.<tag> <flag> <true/false>`

Let me know if it works.
