### ISSUE TITLE
Request: Permissions for Formatting/Colors in /clan setrank

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#548]
I have been having issues with players using &k before their ranks they use in /setrank which is just awful, can we please get permissions for formatting/colors for the clan setrank!
Thanks

**Comment by JH3Y50N** [comment]
poderia por na configuração isso, para que os novos servidores que forem atualizar para a "nova versão" não precisarem por a permissão.. "request-setrank-permission: false"

**Comment by RoinujNosde** [comment]
> poderia por na configuração isso, para que os novos servidores que forem atualizar para a "nova versão" não precisarem por a permissão.. "request-setrank-permission: false"

Ou marcar a permissão como default: true
