### ISSUE TITLE
Request: Permission to deny KDR being effected by people with this perm (new spawns)

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#549]
Had a lot of people farming new spawns to get their KDR high, could we please get a permission I could add to new rank role that when they are killed they are not counted towards peoples KDR.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/issues/276
Would this help?

**Comment by RoinujNosde** [comment]
Are these brand new players civilians? If so, you can add a negative kill weight for civilians in the config.

**Comment by FrozenBeard** [comment]
Yeah, So its just brand new people join the server, and some players take note of their names, wait for their PvP timer to expire, and kill them for K/D as they know they are brand new, which means we lose these brand new players.

The difference is, its the new spawns that are being targeted not just general civilians, since I have a ranking system, I can pinpoint this group, I didnt even think about Negative kill weight, thats even better. 

This is way worse than just normal people, as the normal people are regular players the new spawns need to be treated in their own category almost, getting someone onto your server is hard enough as it is, let alone keeping them, THEN you have people hunting them for K/D, its a losing battle.

What exactly defines a civ?

**Comment by RoinujNosde** [comment]
``What exactly defines a civ?``

Not being in a clan.

**Comment by FrozenBeard** [comment]
For now ive set this:

```
kill-weights:
  rival: 1.5
  civilian: -1.0
  neutral: 0.5
  deny-same-ip-kills: true
```

Some players join together and create a Clan, which would put them in neutral, so it would be nice to have the option for a permission node to protect brand new players from k/d hungry people.

**Comment by RoinujNosde** [comment]
Isn't your spawn protected against PvP?

**Comment by FrozenBeard** [comment]
@RoinujNosde 
Please read up, I have explained I have PvP protection for new spawns.

1. Spawn is obviously PvP free
2. They have a 2 hour PvP protection

I have already said this, players that abuse KDR take note of usernames of new joins and wait until their PvP timer runs out then attack for KDR.

**Comment by RoinujNosde** [comment]
Until this gets implemented, you could increase the PvP protection timer.
