### ISSUE TITLE
Supporting Chatcontrol /ignore

### ISSUE THREAD

**Issue by FrozenBeard** [marcelo-mason/SimpleClans#551]
I've asked both sides as I'm not sure which one should implement! But is there an easy way to use the chat control pro API to use their ignore feature for people in crew and ally chat?

**Comment by RoinujNosde** [comment]
How does this ignore thing work?

**Comment by A248** [comment]
Why would you ignore your own clanmate? Usually ignored players are people who irk you, whom you don't want to work with.

**Comment by FrozenBeard** [comment]
> Why would you ignore your own clanmate? Usually ignored players are people who irk you, whom you don't want to work with.

Some crews have 100 people in, and people can be annoying, just because you are in a crew does not mean you have to like all 100 people in it!



> How does this ignore thing work?
https://github.com/kangarko/ChatControl-Pro/wiki/Developer-API

Hes got an api? In-game players just /ignore <user> and they are ignored from chat/msg which is handed by ChatControl pro.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/events/ChatEvent.java
ChatControl just needs to listen to this event and remove any player that used /ignore from the receivers list (`getReceivers()`).

**Comment by lackoSK** [comment]
Hi there, 

@RoinujNosde 
I was wondering if you have any maven repository because I am unable to find it.

Regards,
lackoSK

**Comment by RoinujNosde** [comment]
@lackoSK I have not

**Comment by lackoSK** [comment]
That was what I was asking for. Thanks...!
