### ISSUE TITLE
Player can set clan tag with &k &n &b......

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#553]
two tags with &k color code http://prntscr.com/r22bz5

i have added the "colors" to config disallowed, i think you can fix in update http://prntscr.com/r22c58

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/74495998-22062b00-4eb8-11ea-83ac-624e1da618e5.png)

Config:
```
  disallowed-tag-colors:
  - '4'
  - k
```

Você provavelmente adicionou o "k" na config depois que o clã escolheu essa tag.

**Comment by RoinujNosde** [comment]
Altere a tag desses dois clãs no banco de dados mesmo...

**Comment by FrozenBeard** [comment]
I actually had this same problem and was going to request a change! 
Thanks!

**Comment by RoinujNosde** [comment]
@FrozenBeard is any change necessary?
The screenshot I took is from the latest version, I didn't change anything...

**Comment by FrozenBeard** [comment]
@RoinujNosde I cant use the latest version, as i'm using 1.12.2 paper :(
So i'm stuck for a while.

**Comment by RoinujNosde** [comment]
> I didn't change anything

The code regarding tag colors is probably the same on your version
