### ISSUE TITLE
clan roster color bug

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#554]
I found this bug on the command /clan roster

&k bug

Print: http://prntscr.com/ri46lq

**Comment by RoinujNosde** [comment]
Qual seria o bug?

**Comment by JH3Y50N** [comment]
> Qual seria o bug?

Então Edson, o cara colocou o código de cor "&k" na tag dele no clan com o /clan setrank e no /clan roster do clã a parte que era para ter uma linha vazia está sendo substituído os espaços pelo "&k" da tag.

**Comment by RoinujNosde** [comment]
Ok, vou cuidar disso
