### ISSUE TITLE
Clan spy new bug

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#555]
I found new bug on the CLAN CHAT SPY

if the player use color codes on the message will be show for admins with colors..

Print: http://prntscr.com/ri4mlm

**Comment by RoinujNosde** [comment]
Você está usando qual versão?

**Comment by JH3Y50N** [comment]
> Você está usando qual versão?

a última, v2.8.1

**Comment by RoinujNosde** [comment]
Consegue me mandar a mensagem que o player **digitou** no chat?
Para que eu possa testar aqui.

**Comment by JH3Y50N** [comment]
não da, eu apaguei os logs do servidor mas eu sei +- oque foi

./clan setrank heroicfight &4&k:::&0Dono&4&k:::

**Comment by JH3Y50N** [comment]
mano agora que fui ver isso ée do legendchat não é do simpleclans...

**Comment by RoinujNosde** [comment]
Haha que bom que descobriu.
Pelo código do SC isso tinha sido corrigido no #550
