### ISSUE TITLE
Player disappears from clan

### ISSUE THREAD

**Issue by xtomyserrax** [marcelo-mason/SimpleClans#560]
Hey, how are you? I have a weird issue going on the server im staff in. A really small amount of players always disappear from the clain they are in. They tried creating their own and they disappear, they join one and they disappear. 

This happens like once a day to them, so could probably happen when server restarts? I asked them to leave the sv and come back again and they dont get out.

Also they are not receiving any message like you were kicked.

Do you know what could be happening or what testing I could ask them to do? The spigot version is latest 1.15.2 and we are using SimpleClans 2.8.2

If you need more info please let me know, though we dont know how to reproduce this. Thanks!

**Comment by RoinujNosde** [comment]
Ask them to create a clan and restart the server; see if they remain in the clan.

Does it happen only to specific players?

**Comment by xtomyserrax** [comment]
Yes it happens to the same players always, I couldnt figure out a pattern, just know this happens with a few of them, not all.

**Comment by RoinujNosde** [comment]
> Ask them to create a clan and restart the server; see if they remain in the clan.

What about this?

**Comment by xtomyserrax** [comment]
Let me show you some screens. I just noticed that with /clan lookup, it seems like he joined for the first time, all his information is reseted every day (maybe with server reloads). I will show you some screens when he was in the clan yesterday (he even appears in /clan bb), and then today he didnt appear in /clan roster and when I did /clan lookup I saw his information that like his profile was created today for the first time.

Here you can see all the screenshots of explanations of everything that happened, let me know if it helps: https://imgur.com/a/n8KgepH

I think his info may have been reloaded with a server restart, I actually cant restart right now as it has people online and Im not the owner, but maybe all the screenshots I sent you are helpful.

Thanks!

**Comment by RoinujNosde** [comment]
No errors on console?
Is there data about him on the database?

**Comment by xtomyserrax** [comment]
Just saw this, when I do /clan lookup CriticLC_ with the player offline, I get this information: https://imgur.com/a/MKHG3c5

Maybe his information is being duplicated? The database is saving information with UUID?

No errors were found in Console. Later we will restart the server to see if his information disappears again

**Comment by RoinujNosde** [comment]
> The database is saving information with UUID?

Yes.

Is your server on online mode?

**Comment by xtomyserrax** [comment]
New screenshots which may give some insights: https://imgur.com/a/hZtFXYL , this player has duplicated data I guess.

Is there a file I could send you for helping, any more info you need? Thanks for your patience and for mantaining this amazing plugin!

**Comment by RoinujNosde** [comment]
So, when he is on, the data is different?

> Is there a file I could send you for helping, any more info you need? 

SimpleClan's db table.

**Comment by xtomyserrax** [comment]
Yep the data is different when he is on and when is off.
I told him to create a clan, we restarted the server and look his clan now: https://imgur.com/a/8dr4oCG
He is no longer in his clan and the clan now has no leader.

I will send the db table as soon as I can!

**Comment by RoinujNosde** [comment]
Also send me your server's latest log.
