### ISSUE TITLE
Clan chat improvements

### ISSUE THREAD

**Issue by xtomyserrax** [marcelo-mason/SimpleClans#563]
Could we check in AsyncPlayerChatEvent for clan chat if the event is cancelled? 

For example it happens in my server that if Im in staffchat and simple clans chat at the same time then I send messages to both chats. Of course Im dumb for not remembering that Im on both of them, but there are some plugins which after the command requires some chat messages and they would also be sent to the clan chat. Dont know what you think about it. 

(Path: src/main/java/net/sacredlabyrinth/phaed/simpleclans/listeners/SCPlayerListener.java)

You could just suround the clan chat part of the event with an if(!event.isCancelled()) or cancel it all (idk if you would like to cancel it all as you may use it for some other things despite it is cancelled)

Thanks!

**Comment by RoinujNosde** [comment]
> Could we check in AsyncPlayerChatEvent for clan chat if the event is cancelled?

Sure.

**Comment by xtomyserrax** [comment]
I can make the pull, but if you want you can do it yourself as you also need to check my other one so you dont need to check more haha

**Comment by RoinujNosde** [comment]
> I can make the pull

Go ahead 👍

**Comment by xtomyserrax** [comment]
I added it in my current Pull Request
