### ISSUE TITLE
Config resets itself

### ISSUE THREAD

**Issue by SaintSaiten** [marcelo-mason/SimpleClans#564]
The plugin works very well and each command/permission seems to be working.

However, the config seems to reset every time the server is restarted or the plugin reloaded.

**Comment by RoinujNosde** [comment]
@SaintSaiten Until this is fixed: after editing the config, do /clan reload or do not edit when the server is on.


https://github.com/marcelo-mason/SimpleClans/blob/f852d9a33a0d90d3c335870dc2540d3dd07a2060/src/main/java/net/sacredlabyrinth/phaed/simpleclans/SimpleClans.java#L115
This is saving the in-memory config to the file.
TODO: Load config from the file before that?
