### ISSUE TITLE
Last seen bug

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#566]
The last seen is not working properly, the player is online but the "/clan lookup" shows that he was seen a month ago, this is happening with several players.

Print: http://prntscr.com/ry2q4t

**Comment by RoinujNosde** [comment]
Notou algum erro no console?

**Comment by JH3Y50N** [comment]
Não, não há erros no console

**Comment by RoinujNosde** [comment]
Na tabela `sc_players` tem a coluna `uuid`, correto?

**Comment by JH3Y50N** [comment]
> Na tabela `sc_players` tem a coluna `uuid`, correto?

Acredito que tenha porque eu resetei o banco de dados, então ele criou um novo...

**Comment by RoinujNosde** [comment]
Mude online-mode para true.

**Comment by JH3Y50N** [comment]
> Mude online-mode para true.

Não, isso estava crashando o servidor e gerando erros http, por isso coloquei o mode em false, meu servidor é pirata não é necessário ficar em true também.

**Comment by RoinujNosde** [comment]
A config "online-mode" do SimpleClans atualmente só serve para causar esse bug do last seen.
Então os crashes devem ter sido causados por outra coisa.

**Comment by JH3Y50N** [comment]
> A config "online-mode" do SimpleClans atualmente só serve para causar esse bug do last seen.
> Então os crashes devem ter sido causados por outra coisa.

então, os erros nos request do console tinha muitos erros da API da Mojang, teria como corrigir o problema do last seen com online-mode: false ?

**Comment by RoinujNosde** [comment]
Qual seria o erro?

**Comment by JH3Y50N** [comment]
> Qual seria o erro?

Era erro na resposta da Mojang ao tentar pegar o UUID do jogador, por isso coloquei o online-mode false

**Comment by RoinujNosde** [comment]
Aparentemente a URL da Mojang está incorreta.

**Comment by JH3Y50N** [comment]
Porque vocês não fazem isso com o UUID normal do jogador?

**Comment by RoinujNosde** [comment]
Esse código era para servidores que não tem UUID. Mas já corrigi isso, logo libero a atualização...

**Comment by JH3Y50N** [comment]
mesmo servidores piratas tem UUID, o UUID não muda em servidores pirata ele é gerado com o nick, "OfflinePlayer:NICK" com o lib do UUID, ou seja o código era meio desnecessário porque o UUID só muda se a pessoa mudar de nick no pirata, e se ela muda de nick ela perde a conta antiga em qualquer servidor pirata, porque não é igual ao original, Obrigado pela correção estou aguardando ela

**Comment by RoinujNosde** [comment]
> Esse código era para servidores que não tem UUID. 

Falo de versões anteriores a 1.7.
