### ISSUE TITLE
MySQL error 'incorrect string value'

### ISSUE THREAD

**Issue by luiswenner** [marcelo-mason/SimpleClans#567]
![Screenshot_2](https://user-images.githubusercontent.com/10003830/79083678-1becc900-7d06-11ea-80e1-528b08bd26e3.png)
![Screenshot_3](https://user-images.githubusercontent.com/10003830/79083679-1d1df600-7d06-11ea-9576-7d1dbd935b8a.png)
![Screenshot_4](https://user-images.githubusercontent.com/10003830/79083680-1d1df600-7d06-11ea-8b24-9cf1ba1cb648.png)

MySQL error 'incorrect string value'
I'm having problems with mysql, related to mysql, when some change is made to the clans, apparently it is not saved as it should in the mysql tables. apparently involves special characters. my apologies for the english, i'm using google translator

**Comment by RoinujNosde** [comment]
Posta o erro no pastebin.com, por favor.

**Comment by luiswenner** [comment]
https://pastebin.com/XnSgpHwJ
prontinho ta na nao, minhas desculpas pelos erros no slimefun, ignore-os, ja reportei o bug, e estou aguardando uma solução
os erros estão nas linhas 1682, 1795, 1832, 1966, 2141, 2168, 2206 entre outras.
obrigada pela atenção!

**Comment by RoinujNosde** [comment]
Sim, o problema são caracteres especiais. Acho que tenho uns solução para isso. Vou testar à tarde.

**Comment by RoinujNosde** [comment]
Aqui rodou sem problemas:
![image](https://user-images.githubusercontent.com/6441328/79175033-e95cd200-7dd2-11ea-9b5c-aa937fcdcd20.png)


Você consegue deixar o seu MySQL como na imagem abaixo?
![image](https://user-images.githubusercontent.com/6441328/79175126-3b9df300-7dd3-11ea-820b-317e0dc38d7a.png)

**Comment by luiswenner** [comment]
me passa o comando pra mim testar pf!
O meu esta assim
https://prnt.sc/rytu6s

**Comment by RoinujNosde** [comment]
[SimpleClans.zip](https://github.com/marcelo-mason/SimpleClans/files/4474928/SimpleClans.zip)

Teste se o problema é resolvido nesse jar, por favor.

**Comment by luiswenner** [comment]
infelizmente o erro persiste!
![download](https://user-images.githubusercontent.com/10003830/79291798-f696c100-7ea5-11ea-8fb6-1b7358ff0d81.png)

**Comment by RoinujNosde** [comment]
Deu algum erro ou aviso do SimpleClans assim que o servidor iniciou?

**Comment by luiswenner** [comment]
desculpe a demora, bom basicamente fiz as alterações
![Screenshot_9](https://user-images.githubusercontent.com/10003830/79742462-3bbd5780-82d9-11ea-8dbe-1794e0bed37c.png)
 salvei, e tentei reiniciar o serviço pra ver se tinha algum erro e apareceu o erro abaixo do próprio mysql, nao arisquei ligar o servidor pra não corromper nada.
em relação a inicialização, nao aparece nenhum erro inicia e desliga normal

**Comment by RoinujNosde** [comment]
Faça um backup dos dados e teste.

**Comment by luiswenner** [comment]
mais o serviço do mysql nao funciona, então como irei testar ?

**Comment by RoinujNosde** [comment]
Tem algum log de erro?

**Comment by luiswenner** [comment]
nao iniciei pra testar, mais se nen liga o mysql como vou testar nele.
na inicialização nao da nenhum erro no plugin de fato. aparentemente e a forma que salva nas tabelas do mysql

**Comment by RoinujNosde** [comment]
> Tem algum log de erro?

Do MySQL.
Não gerou nenhum arquivo "nome da host".err?

**Comment by luiswenner** [comment]
somente o da imagem que enviei, se tiver outro nao sei onde encontro. minhas desculpas se nao consigo ser tao especifico com o mysql, nao e muito minha praia

**Comment by RoinujNosde** [comment]
Pasta /var/log
