### ISSUE TITLE
SimpleClans is lagging

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#568]
![image](https://user-images.githubusercontent.com/29031972/79095493-ea3d2780-7d30-11ea-8280-64b1e245684a.png)

Commands:
/clan accept
/clan deny

**Comment by RoinujNosde** [comment]
Me mande a sua config.

**Comment by JH3Y50N** [comment]
`
safe-civilians: false
tag:
  default-color: b
  max-length: 3
  bracket:
    color: '7'
    leader-color: '7'
    left: '['
    right: ']'
  min-length: 2
  separator:
    color: '7'
    leader-color: '7'
    char: ''
settings:
  online-mode: false
  disable-messages: true
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  mchat-integration: false
  enable-auto-groups: false
  chat-compatibility-mode: false
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: false
  display-chat-tags: false
  unrivable-clans:
  - admin
  - staff
  - mod
  - vip
  - v1p
  - adm
  - bot
  - tst
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - admin
  - staff
  - mod
  - vip
  - v1p
  - adm
  - bot
  - tst
  language: pt-br
  disallowed-tag-colors:
  - '4'
  - '0'
  - k
  - m
  - n
  - o
  - r
  - l
  server-name: '&7[&4M&aC&7]&b'
  new-clan-verification-required: false
  allow-regroup-command: false
  allow-reset-kdr: false
  rejoin-cooldown: 60
  rejoin-cooldown-enabled: false
kdr-grinding-prevention:
  enable-max-kills: false
  max-kills-per-victim: 10
  enable-kill-delay: false
  delay-between-kills: 5
list:
  size: size
  kdr: kdr
  name: name
  founded: founded
  active: active
  asc: asc
  desc: desc
  default: kdr
commands:
  more: mais
  ally: ally
  clan: clan
  accept: aceitar
  deny: negar
  global: global
  clan_chat: .
  force-priority: true
economy:
  creation-price: 10000000
  purchase-clan-create: true
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 1000000.0
  purchase-clan-invite: true
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  home-regroup-price: 5.0
  purchase-home-regroup: false
  unique-tax-on-regroup: true
  issuer-pays-regroup: true
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
  purchase-reset-kdr: true
  reset-kdr-price: 10000.0
  purchase-member-fee-set: false
  member-fee-set-price: 1000.0
  member-fee-enabled: false
  max-member-fee: 200.0
  upkeep: 200.0
  upkeep-enabled: false
  multiply-upkeep-by-clan-size: false
  charge-upkeep-only-if-member-fee-enabled: true
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
  deny-same-ip-kills: false
clan:
  homebase-teleport-wait-secs: 3
  homebase-can-be-set-only-once: false
  min-size-to-set-rival: 3
  max-length: 32
  max-description-length: 120
  min-description-length: 10
  max-members: 15
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  percentage-online-to-demote: 100.0
  ff-on-by-default: false
  min-length: 2
  min-size-to-set-ally: 3
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 20
clanchat:
  enable: true
  tag-based-clan-chat: false
  announcement-color: e
  format: '&b[%clan%&b] &4<%nick-color%%player%&4> %rank%&b%message%'
  rank: '&f[%rank%&f]: '
  leader-color: '4'
  member-color: f
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
  login-size: 6
allychat:
  enable: true
  format: '&b[Clan Ally] &4<%clan%&4> <%nick-color%%player%&4> %rank%&b%message%'
  rank: '&f[%rank%&f]: '
  leader-color: '4'
  member-color: f
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  use-threads: true
  use-bungeecord: false
`

**Comment by RoinujNosde** [comment]
Parece que o culpado é o SQLite.
Vi que você marcou "use-threads" como true, mas as conexão do SQLite não estão usando isso, então tá indo no main thread.
Vou corrigir isso para ver se resolve o lag.

**Comment by JH3Y50N** [comment]
eu marquei para true para ver se o lag parava mas não adiantou nada

**Comment by JH3Y50N** [comment]
still lagging check https://timings.aikar.co/?id=a52c3834548e467c986b5a709cf3feab

**Comment by RoinujNosde** [comment]
use-threads está false?

**Comment by JH3Y50N** [comment]
> use-threads está false?

sim está em false, queria testar o problema, mesmo ele estando em false ou em true continua lagando então é isso.

**Comment by RoinujNosde** [comment]
Mande um timings com o use-threads true.

**Comment by JH3Y50N** [comment]
> Mande um timings com o use-threads true.

vou adiantar, já mandei um antes e o simpleclans não aparecia, mas o simpleclans está causando o lag de CPU usando Threads, ele usa muito CPU assim fazendo o load subir

**Comment by RoinujNosde** [comment]
Com use-threads false não tem milagre que eu possa fazer.

**Comment by JH3Y50N** [comment]
> Com use-threads false não tem milagre que eu possa fazer.

conexão SQL é aberta cada vez que o plugin faz uma nova query ou ela fica aberta até dar time out?

**Comment by RoinujNosde** [comment]
Fica aberta durante a execução do plugin.

**Comment by JH3Y50N** [comment]
> Fica aberta durante a execução do plugin.

então como ele consegue lagar com uma conexão SQL, já pensou em usar flatfile em modo yml ou json? talvez reduza o lag porque acredito que seja o SQL que esteja lagando, uma boa é fazer o plugin salvar tudo em cache e guardar as coisas no banco de dados perioticamente em modo Async ou salvar quando o cache tiver muitas modificações criticas que precisem ser salvas, neste caso ele iria salvar o cache todo

**Comment by RoinujNosde** [comment]
O SC já guarda os dados em cache e salva de modo async se ativar "use-threads".

Ative a opção e rode o timings no horário que você percebe o maior lag.
Pode ser algum outro plugin causando isso...

**Comment by JH3Y50N** [comment]
> O SC já guarda os dados em cache e salva de modo async se ativar "use-threads".
> 
> Ative a opção e rode o timings no horário que você percebe o maior lag.
> Pode ser algum outro plugin causando isso...

sim mas pelo que notei você salva constantemente os novos dados do cache, isso criando muitas queries no SQL

**Comment by RoinujNosde** [comment]
Mas de forma async.

**Comment by JH3Y50N** [comment]
> Mas de forma async.

sim de forma Async, ou seja continua usando CPU fazendo o load do CPU subir causando um lag em toda a máquina

**Comment by RoinujNosde** [comment]
> Ative a opção e rode o timings no horário que você percebe o maior lag.
Pode ser algum outro plugin causando isso...

**Comment by JH3Y50N** [comment]
> > Ative a opção e rode o timings no horário que você percebe o maior lag.
> > Pode ser algum outro plugin causando isso...

deixa, irei fazer um plugin de clã novo acho que isso irá resolver meu problema, de qualquer forma enquanto eu estiver usando o SimpleClans irei reportar os problemas que eu encontrar.

**Comment by RoinujNosde** [comment]
Sim, fazer um plugin realmente é mais simples do que rodar um teste...

**Comment by RoinujNosde** [comment]
Resolvi implementar o salvamento periódico:
[SimpleClans-v.2.10.2.zip](https://github.com/marcelo-mason/SimpleClans/files/4584183/SimpleClans-v.2.10.2.zip)

Me diga se resolve o lag...

**Comment by JH3Y50N** [comment]
> Resolvi implementar o salvamento periódico:
> [SimpleClans-v.2.10.2.zip](https://github.com/marcelo-mason/SimpleClans/files/4584183/SimpleClans-v.2.10.2.zip)
> 
> Me diga se resolve o lag...

ok, coloquei no servidor amanhã vejo quando

**Comment by JH3Y50N** [comment]
https://timings.aikar.co/?id=e2d678b5e83b471d965d8a858e28fc66

média de 100 jogadores online, quando tiver uns 200 eu mando outro timings

Praticamente todo o lag foi causado pela task que salva
![image](https://user-images.githubusercontent.com/29031972/81360776-14c19c80-90b3-11ea-8954-156ed8bcdf60.png)

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/blob/6083766a121ac3d6b7f5c1ab3508e9a19fea884e/src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java#L1500

Parece que esse é o culpado.

**Comment by JH3Y50N** [comment]
> https://github.com/marcelo-mason/SimpleClans/blob/6083766a121ac3d6b7f5c1ab3508e9a19fea884e/src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java#L1500
> 
> Parece que esse é o culpado.

se ele está causando lag são os métodos ali o problema, tem que ser optimizado se possível.

**Comment by RoinujNosde** [comment]
> o problema é no "delete" do clã, por conta do SQL.

Exatamente.
Qual seria a sua sugestão para resolver?

**Comment by JH3Y50N** [comment]
> > o problema é no "delete" do clã, por conta do SQL.
> 
> Exatamente.
> Qual seria a sua sugestão para resolver?

deixar o sistema todo em cache e salvar o SQL em uma batch só de tempos em tempos em modo Async, não ficar enviando um milhão de queries para o SQL ajuda... envie menos queries..

**Comment by RoinujNosde** [comment]
![81360776-14c19c80-90b3-11ea-8954-156ed8bcdf60](https://user-images.githubusercontent.com/6441328/81435794-cce85700-913e-11ea-8d44-878a54e80bbe.png)
A contagem foi de apenas 1 task, como você pode ver em `count(1)`.
Batch nesse caso parece ser desnecessário, não é a todo minuto que se deleta um clã.
(No caso dos updates, faz sentido, porque no último timings tinham umas mil queries. Mas nessa correção já estão em batch)

**Comment by RoinujNosde** [comment]
Testou novamente com mais players?

**Comment by JH3Y50N** [comment]
> Testou novamente com mais players?

https://timings.aikar.co/?id=5e7980e7db49407695c9c2efed0cafb2 em um final de semana eu mando outro, mas teme esse com 120

**Comment by RoinujNosde** [comment]
Parece ter resolvido.
Sobre o clan delete, ativando use-threads resolve. (Não vai ter milhares de async tasks)

Vou fechar aqui. Se aparecer o lag no fim de semana, me avise.
