### ISSUE TITLE
My prefixes do not work in a tab

### ISSUE THREAD

**Issue by Denias3** [marcelo-mason/SimpleClans#569]
My prefixes do not work in a tab
I used this instruction
https://github.com/marcelo-mason/SimpleClans/wiki/Displaying-the-clan-tag-on-the-tablist
But it does not work

**Comment by RoinujNosde** [comment]
What version are you using?

**Comment by Denias3** [comment]
> What version are you using?

2.8.3v

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/79486733-82673500-7fed-11ea-8820-06445ebd95e9.png)
Working on latest version.

What is your PlayerListPlus config?

**Comment by Denias3** [comment]
I am using https://www.spigotmc.org/resources/tab-1-5-x-1-15-x-free-version.57806/
But I think this is not the problem. Because after using the "/papi ecloud download simpleclans" command
I can not find your plugin in "/papi list"

**Comment by Denias3** [comment]
I wanted to update your plugin and check if this problem exists. But your new plugin did not load the old database. I know that you fixed it, as soon as I can verify I will inform you

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/79619206-980a5680-80e2-11ea-90d7-9aead85f07ac.png)



> Because after using the "/papi ecloud download simpleclans" command

Any error on console after using this command?

**Comment by JH3Y50N** [comment]
the simpleclans api have updated and the plugin uses outdated api.. make a console error maybe?

**Comment by Denias3** [comment]
![image](https://user-images.githubusercontent.com/36571895/79810399-a2934d00-837b-11ea-8f93-5a75c26f1096.png)
there are no errors in the chat and console.
On the new version, it still does not work

**Comment by Denias3** [comment]
![image](https://user-images.githubusercontent.com/36571895/79810641-32d19200-837c-11ea-9b3e-14866da018e3.png)
![image](https://user-images.githubusercontent.com/36571895/79810736-5694d800-837c-11ea-8e09-bfed071d799c.png)

But if you use "/papi reload" you get an error in the console and chat

**Comment by RoinujNosde** [comment]
Some expansion needs LuckPerms.

**Comment by Denias3** [comment]
What should I do?

**Comment by RoinujNosde** [comment]
Can you install it to see if everything works?
Unless you have a different permissions plugin.

**Comment by Denias3** [comment]
I have luckperms installed

**Comment by RoinujNosde** [comment]
Latest version of LuckPerms?

**Comment by Denias3** [comment]
not 4.4.1

**Comment by RoinujNosde** [comment]
Try the latest version.

**Comment by Denias3** [comment]
It worked. Thanks
