### ISSUE TITLE
Crashing on server stop

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#572]
Clan setrank missing messages.. http://prntscr.com/s0q762
And more this http://prntscr.com/s0q90g

My tps afer the update.. http://prntscr.com/s0q7zx

**Comment by RoinujNosde** [comment]
> Clan setrank missing messages..

As mensagens que estão faltando estão no language.yml dentro do jar.

> My tps afer the update..

Manda o timings.

**Comment by JH3Y50N** [comment]
estou analisando o timings aqui pra ver se é o SimpleClans mesmo, você deveria ter colocado as novas mensagens.. vou fazer alguns testes para ver se foi o SimpleClans que lagou o servidor ou a config do spigot.

**Comment by JH3Y50N** [comment]
fui desligar o servidor e o plugin de clã crashou ele, esses últimos updates vieram muito bugados...

http://prntscr.com/s0qjqw

**Comment by RoinujNosde** [comment]
Veja se consegue rodar o timings.

**Comment by JH3Y50N** [comment]
Rodei o timings, mas parece que não é o simpleclans que está causando o lag..
https://timings.aikar.co/?id=8c77ddf86ab34cf08be184de48d39c97

**Comment by RoinujNosde** [comment]
> você deveria ter colocado as novas mensagens

No arquivo BR?

> fui desligar o servidor e o plugin de clã crashou ele

Tente novamente

**Comment by JH3Y50N** [comment]
sim no arquivo BR, você não avisou sobre nova mensagens e como que comandos antigos que já existiam no plugin bugaram como /clan setrank se já existem mensagens dele? acho que o sistema de mensagens bugou...

**Comment by RoinujNosde** [comment]
O /setrank foi modificado 
Esqueci de pôr as mensagens no arquivo BR, estão apenas no principal.
O sistema atual de mensagens é ruim.

**Comment by JH3Y50N** [comment]
tem como você atualizar o sistema então?

**Comment by RoinujNosde** [comment]
Vou ver o que posso fazer.

**Comment by RoinujNosde** [comment]
Você nem precisa esperar, as mensagens que estão faltando estão no final do arquivo original.
Só copiar para o seu.

**Comment by JH3Y50N** [comment]
então no arquivo br original dentro do plugin?

**Comment by RoinujNosde** [comment]
> então no arquivo br original dentro do plugin?

language.yml

**Comment by JH3Y50N** [comment]
sim, vou fazer a tradução dessas últimas linhas obrigado.

**Comment by RoinujNosde** [comment]
:+1:

**Comment by JH3Y50N** [comment]
cara, essa versão ainda está bugada, quando desliga o servidor ela crasha no console durante o desligamento, sem dizer que meu servidor está lagando e não sei dizer se ela é ela porque você usa threads no sistema.. e não aparece no timings, o loss do TPS passando de 80% e ela crasha quando reinicia o servidor.

**Comment by RoinujNosde** [comment]
Veja se crasha com essa versão:
[SimpleClans-v2.9.3.zip](https://github.com/marcelo-mason/SimpleClans/files/4490022/SimpleClans-v2.9.3.zip)

**Comment by JH3Y50N** [comment]
não posso mais reiniciar o servidor, os jogadores já ficaram pistola comigo, vou testar ela amanhã te aviso se der tudo certo.

**Comment by RoinujNosde** [comment]
`/home/op/hs_err_pid18205.log`
Poste esse arquivo, enquanto isso.

**Comment by JH3Y50N** [comment]
[hs_err_pid18205.log](https://github.com/marcelo-mason/SimpleClans/files/4490426/hs_err_pid18205.log)

**Comment by RoinujNosde** [comment]
[SimpleClans-v2.9.3.zip](https://github.com/marcelo-mason/SimpleClans/files/4492426/SimpleClans-v2.9.3.zip)
Na verdade, tente com esse arquivo. Fiz uma alteração.

**Comment by JH3Y50N** [comment]
O problema do lag foi resolvido, eu testei aquela primeira versão que você mandou quando o servidor reiniciou não crashou, essa nova que você enviou só vou poder testar ela amanhã

**Comment by RoinujNosde** [comment]
Continua rodando bem? Testou a nova versão?

**Comment by JH3Y50N** [comment]
opa, vi o log aqui e não crashou dessa vez, meu servidor reinicia todos os dias as 5 da manhã e o log estava normal.

**Comment by RoinujNosde** [comment]
Isso já com a nova versão que eu passei?

**Comment by JH3Y50N** [comment]
Sim com ela

**Comment by JH3Y50N** [comment]
No log só apareceu que o plugin estava desativando mais nenhuma mensagem de log nem nada somente que ele estava desligando igual a todos os outros plugins
