### ISSUE TITLE
Improve language system

### ISSUE THREAD

**Issue by RoinujNosde** [marcelo-mason/SimpleClans#573]
1. If a message is not present in a language, use the main file.

**Comment by xtomyserrax** [comment]
Good idea, also what about multi language support? The actual language system is really good, you actually have a player as parameter and the preference can be saved in ClanPlayer.

Basicly a player could do /clan language english and another /clan language spanish ; Both players will get their SimpleClans messages in their own language. The only thing that this would require is to have translations (in my case I can help with spanish). The only thing that this would need is to have all languages files enabled in memory (or maybe just have loaded the one the server owner wants, which he can say that in the config.yml file)

**Comment by JH3Y50N** [comment]
> Good idea, also what about multi language support? The actual language system is really good, you actually have a player as parameter (so there is no need to change all messages sent) and the preference of the player can be saved in ClanPlayer being english or the specified in config.yml file the default one.
> 
> Basicly a player could do /clan language english and another /clan language spanish ; Both players will get their SimpleClans messages in their own language. The only thing that this would require is to have translations (in my case I can help with spanish). The only thing that this would need is to have all languages files enabled in memory (or maybe just have loaded the one the server owner wants, which he can say that in the config.yml file)

good ideia
