### ISSUE TITLE
Cant demote leaders from a clan

### ISSUE THREAD

**Issue by xtomyserrax** [marcelo-mason/SimpleClans#575]
There is a small issue when trying to demote a leader from a clan in which 100% online requirement will never be reached (it can be changed in config file)

As you can see in this picture, the three leaders of the clan are online but we cant use the demote command. https://imgur.com/a/oq0L2vM

In line 1217 from [this code](https://github.com/marcelo-mason/SimpleClans/blob/a9fe5897945fa2a499d53234f6f781f98ec849f9/src/main/java/net/sacredlabyrinth/phaed/simpleclans/Clan.java#L1215) it deletes the online leader trying to be demoted, so after what we talked, the tolta amount of leaders should also be decreased by one.

And this is as a question: a leader can demote a clan owner/creator? Maybe a new rank could be created so there would be: owner, leader, trusted, untrusted. So owner could never be demoted but yes he could give his ownership (maybe like Supercell clans work), and leaders will have same perms as owner except demoting him or changing owner. If owner leaves the clan, then a leader takes his place or a random member if there is no other leader (?

Thanks!

**Comment by JH3Y50N** [comment]
co leader better, "second leader"

Leader
Co Leader
Trusted
Member

**Comment by RoinujNosde** [comment]
> And this is as a question: a leader can demote a clan owner/creator? Maybe a new rank could be created so there would be: owner, leader, trusted, untrusted. So owner could never be demoted but yes he could give his ownership (maybe like Supercell clans work), and leaders will have same perms as owner except demoting him or changing owner. If owner leaves the clan, then a leader takes his place or a random member if there is no other leader (?

They can do that with the rank update.
/clan rank create coleader

Then add all permissions to it. This way the coleader wouldn't be able to disband the clan or demote another a leader.
