### ISSUE TITLE
You do not have leader permissions!

### ISSUE THREAD

**Issue by xZiomeczeQ** [marcelo-mason/SimpleClans#576]
I created a clan, offered an alliance and a message popped up like in the title - what's wrong? All permissions with OP enabled and still the same.

**Comment by RoinujNosde** [comment]
Latest version?

**Comment by xZiomeczeQ** [comment]
Yeah, 2.9.2 version on 1.15.2 Spigot...

**Comment by xZiomeczeQ** [comment]
My players created their clans, I verified them - then I entered / clan profile [clan id] and displays no leaders - it is impossible to create an alliance or to mark someone as a rival.

**Comment by RoinujNosde** [comment]
Any console error?

**Comment by xZiomeczeQ** [comment]
I have no idea how, but when I decided to do it myself, everything got fixed - to close!

**Comment by RoinujNosde** [comment]
😎
