### ISSUE TITLE
KDR does not work

### ISSUE THREAD

**Issue by Denias3** [marcelo-mason/SimpleClans#579]
KDR never changes. Even if different clans kill each other
config https://pastebin.com/n16sp2xv

**Comment by Denias3** [comment]
SimpleClans v2.9.2
luckPerms 5.0.136

**Comment by RoinujNosde** [comment]
Try denying this permission: simpleclans.anyone.kdr-exempt

**Comment by JH3Y50N** [comment]
> Try denying this permission: simpleclans.anyone.kdr-exempt

add to deny by default this permission...

**Comment by RoinujNosde** [comment]
@JH3Y50N does the same happen to you?

**Comment by JH3Y50N** [comment]
> @JH3Y50N does the same happen to you?

yes, but i have dened the permission to solve this and now is working fine

**Comment by Denias3** [comment]
thanks

**Comment by RoinujNosde** [comment]
> add to deny by default this permission...

@JH3Y50N todo mundo provavelmente dá essa perm:
`simpleclans.anyone.*`
E a de KDR vai junto.

Vou mudar o nome da permissão...
