### ISSUE TITLE
Add Clan Chat to /clan menu

### ISSUE THREAD

**Issue by xtomyserrax** [marcelo-mason/SimpleClans#582]

**Comment by xtomyserrax** [comment]
Add /. join/leave to the clan menu

**Comment by JH3Y50N** [comment]
add :) that's a good feature

**Comment by msudol** [comment]
how does clan chat work anyway?  can't seem to figure it out..

**Comment by RoinujNosde** [comment]
> how does clan chat work anyway? can't seem to figure it out..

Clan members can talk with each other using the command /.
Example:
/. hello

You can change the dot to whatever you want in the config. (The clan tag, for instance, or any other word)

**Comment by RoinujNosde** [comment]
Also add /ally <message>

And add those commands to the Chat Button.
