### ISSUE TITLE
Clan tag on LegendChat

### ISSUE THREAD

**Issue by Victorhlima12** [marcelo-mason/SimpleClans#586]
I don't know what's going on...
![Capturar](https://user-images.githubusercontent.com/64282745/80491762-87a37880-8939-11ea-88d5-3a6f384c7ba5.JPG)

**Comment by Victorhlima12** [comment]
It's the world name

**Comment by RoinujNosde** [comment]
Ali deveria estar a TAG do Clan?

**Comment by Victorhlima12** [comment]
isso... 
a config do lc ta assim: 
![Capturar2](https://user-images.githubusercontent.com/64282745/80492062-e537c500-8939-11ea-9815-b4f2ad57cb56.JPG)

**Comment by RoinujNosde** [comment]
Você já testou com {clan}?

**Comment by Victorhlima12** [comment]
com {bprefix} e {clan}:
![Capturar3](https://user-images.githubusercontent.com/64282745/80492323-3942a980-893a-11ea-9d2f-eaa71691694a.JPG)

**Comment by RoinujNosde** [comment]
Você marcou "use_async_chat_event" como true?

**Comment by Victorhlima12** [comment]
sim

**Comment by RoinujNosde** [comment]
Tente {clantag}

**Comment by RoinujNosde** [comment]
![image](https://user-images.githubusercontent.com/6441328/80515570-8897d280-8958-11ea-9291-88a0e61655d4.png)
Apenas coloquei os dois plugins no servidor e iniciei. Não configurei nada.

**Comment by Victorhlima12** [comment]
foi também não

**Comment by Victorhlima12** [comment]
vou tentar resolver por aqui

**Comment by RoinujNosde** [comment]
Conseguiu?

**Comment by JH3Y50N** [comment]
em meu servidor fiz um Addon para que eu pudesse controlar melhor as tags do clã, usando o LegendChat mesmo, também corrigindo alguns "7k" e "&L" que os jogadores botavam na tag do clã kk
