### ISSUE TITLE
Money bank dup

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#588]
Portuguese: O simpleclans está duplicando o money dos jogadores, já aconteceu duas vezes em meu servidor a duplicação do money, irei deixar uma print do meu staffer explicando.

http://prntscr.com/s89gk2

Ele diz que o servidor "caiu" mas não caiu foi um pico de lag que acredito que foi causado também pelo SimpleClans.

**Comment by RoinujNosde** [comment]
E o timings?

**Comment by JH3Y50N** [comment]
no timings não mostra nada, você usa Threads no plugin.... sobre ele dizer que o servidor "caiu" duas vezes ele não caiu o uptime tava em 14 horas, porque meu servidor reinicia todos os dias as 5 da manhã.

**Comment by RoinujNosde** [comment]
Lag é causado quando algo bloqueia (salvar arquivos, acessar db, etc) o thread principal.
O SimpleClans não está mexendo com o db no thread principal, então não deveria causar lag.
Se quiser testar com a nova versão do plugin, eu troquei de Thread para AsyncTask, pode ser que o Bukkit gerencie de forma melhor as tarefas...

**Comment by JH3Y50N** [comment]
fiz download da v 10 vou testar ela

**Comment by JH3Y50N** [comment]
bem, até agora na v 10 tudo bem, se tiver algum problema eu aviso.
