### ISSUE TITLE
Maven Question

### ISSUE THREAD

**Issue by Peng1104** [marcelo-mason/SimpleClans#589]
Does SimpleClans still have a maven repository?

**Comment by RoinujNosde** [comment]
Nope, but you can use the GitHub repo as a dependency with [JitPack](https://jitpack.io/)

**Comment by Peng1104** [comment]
> Nope, but you can use the GitHub repo as a dependency with [JitPack](https://jitpack.io/)
Thx I will use the [JitPack](https://jitpack.io/) than
