### ISSUE TITLE
globalff allow/auto 

### ISSUE THREAD

**Issue by mikengaid** [marcelo-mason/SimpleClans#594]
## Something wrong with /clan ff and /clan globalff
I'm using `paper-282`(Worldguard, and some other plugins,that doesn't affect at simpleClans).  
Minecraft version `1.15.2`.  
Command globalff and ff doesn't work properly.
When i try to allow or deny globalff i got a message: usage /clan ff auto/allow"
### Here is the message bellow (I'm using russian locale).
![image](https://user-images.githubusercontent.com/44208909/81874812-68d2f200-9587-11ea-9e1f-29fc2db82966.png)
The same message i got when enter "/clan ff allow" in game.
**Am i using this command incorrectly? Or it is a bug!?**

**Comment by RoinujNosde** [comment]
There are two problems here:
"auto" and "allow" were translated only in one place.
The globalff command is getting the usage of the ff command.
