### ISSUE TITLE
KDR Not calculating

### ISSUE THREAD

**Issue by Luwnett** [marcelo-mason/SimpleClans#595]
So, pretty much it, the plugin wouldn't calculate KDR
Sometimes it wont calculate kills neither, i need help with it.
![image](https://user-images.githubusercontent.com/65328206/81894764-fbbf5c80-9586-11ea-9c78-3514c5b7588d.png)
![image](https://user-images.githubusercontent.com/65328206/81894778-02e66a80-9587-11ea-9770-2419d46bc4a5.png)
![image](https://user-images.githubusercontent.com/65328206/81894787-0974e200-9587-11ea-9e71-2b0c62ac9df5.png)

**Comment by Luwnett** [comment]
Sorry i got nervous and fixed it by verifing the clan

**Comment by RoinujNosde** [comment]
Então se o clã não está verificado, não calcula o KDR?

**Comment by Luwnett** [comment]
Perdão pela meu topico criado sem nescessidade,
Meu problema era que o PVPstats estava conflitando com a contagem do Simpleclans, e não calculava as kills/deaths
Resolvi isso removendo o PVPstats e atualizando-o
Meu segundo problema foi que ele não calculava o KDR, mas quando percebi estava apenas matando civis e o peso de civis no kdr era 0

**Comment by RoinujNosde** [comment]
Sem problemas. Pode criar tópico sempre que tiver dúvidas.
