### ISSUE TITLE
Set tag as sufix

### ISSUE THREAD

**Issue by Beartherter13** [marcelo-mason/SimpleClans#596]
In my chat I see clan TAG fir first, before the prefix. I need to do after the prefix, how to do it?
I`m use ChatManager_3.6.4 plugin

**Comment by RoinujNosde** [comment]
In your ChatManager config, add %simpleclans_clan_color_tag% to where you need the tag.
Something like:
`Default_Format: "&8[&7Default&8] &7{player} %simpleclans_clan_color_tag% &9> &7{message}"`

You need [PlaceholderAPI ](https://www.spigotmc.org/resources/placeholderapi.6245/)for that.
