### ISSUE TITLE
Remove a disband message

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#597]
Message to remove: http://prntscr.com/sjcpwu

i have disabled the messages in the configuration but still showing

**Comment by RoinujNosde** [comment]
Como você removeu a mensagem?
Apagou a linha inteira ou deixou a key?

**Comment by JH3Y50N** [comment]
> Como você removeu a mensagem?
> Apagou a linha inteira ou deixou a key?

![image](https://user-images.githubusercontent.com/29031972/82277973-832e1680-995f-11ea-9a58-75b9160e3abc.png)

**Comment by RoinujNosde** [comment]
No seu arquivo de mensagens, procure essa linha:
`clan.has.been.disbanded=`
E apague tudo depois do =

**Comment by JH3Y50N** [comment]
> No seu arquivo de mensagens, procure essa linha:
> `clan.has.been.disbanded=`
> E apague tudo depois do =

mas irá enviar uma linha em branco no chat.
