### ISSUE TITLE
Too long colored tag

### ISSUE THREAD

**Issue by LoSCraft-Network** [marcelo-mason/SimpleClans#598]
Good afternoon,

We've been having a problem that modifications to a clan tag aren't being saved, they rollback after a while and today I found this error on the console:

Here is the error:
[https://pastebin.com/gCQpt5cK](url)

We're using SimpleClans verison 2.10.3
And tuinity git-tuinity-"6eb873c" (MC 1.15.2)

**Comment by RoinujNosde** [comment]
What tag was set?

**Comment by LoSCraft-Network** [comment]
&7&mI&c&l&mc&4&lD&c&l&mc&7&mI

**Comment by RoinujNosde** [comment]
That's a long tag.
I'm going to add a check for the tag size.

**Comment by LoSCraft-Network** [comment]
So if the tag is shortened it should work fine?
How long should I tell him to keep the tag?
Also, does the length include the color codes or only the letters?

**Comment by RoinujNosde** [comment]
> Also, does the length include the color codes or only the letters?

Both.

> So if the tag is shortened it should work fine?
How long should I tell him to keep the tag?

Yes. 25 characters or less.

**Comment by LoSCraft-Network** [comment]
Thank you!

**Comment by RoinujNosde** [comment]
Add check on modtag command.
