### ISSUE TITLE
Requests/"Bugs" on the new GUI

### ISSUE THREAD

**Issue by danielpeter99** [marcelo-mason/SimpleClans#607]
Good afternoon,

I updated to the newest version and we love the new GUI

I found some "Bugs", not really a bug but something that doesn't work as it should

The GUI-Menu isn't translatable yet (At least I couldn't find it on the messages or on the config
My server is a Brazilian server, all our plugins are translated to portuguese, having the option to translate the GUI menu so it doesn't go out of pattern nor makes someone's game harder because they don't speak english

Also, when selecting the leaderboard, many of the heads do not have skin or are mobs as shown below
[https://i.imgur.com/ITHfLUl.png](https://i.imgur.com/ITHfLUl.png)

It would be nice if the banner shown in the Clan-list could be editable by players

**Comment by RoinujNosde** [comment]
> The GUI-Menu isn't translatable yet

What language did you set? I translated to Portuguese myself. Try setting it to "pt_BR".

> It would be nice if the banner shown in the Clan-list could be editable by players

#599 if you have any additions to this suggestion, comment there.

> Also, when selecting the leaderboard, many of the heads do not have skin or are mobs as shown below

And they are premium accounts?

**Comment by danielpeter99** [comment]
> And they are premium accounts?
Most likely not, is there a way to get heads for the non-premium accounts?

I downgraded to the previous version, **/clan** command was freezing the server

**Comment by RoinujNosde** [comment]
> Most likely not, is there a way to get heads for the non-premium accounts?

I don't know.

> I downgraded to the previous version, /clan command was freezing the server

Can you run timings and paste the result here?

**Comment by SrBedrock** [comment]
It would be interesting to be able to define an item to be used in the empty slots of the GUI.

![image](https://user-images.githubusercontent.com/51332006/83219583-1bd64a80-a147-11ea-89e6-39b3d219e7eb.png)
