### ISSUE TITLE
Placeholders for top clans

### ISSUE THREAD

**Issue by RoinujNosde** [marcelo-mason/SimpleClans#610]
%simpleclans_topclans_POSITION_color_tag%
%simpleclans_topclans_POSITION_kdr%
%simpleclans_topclans_POSITION_total_kills%

**Comment by xtomyserrax** [comment]
That might not be compatible with this: https://github.com/marcelo-mason/SimpleClans/issues/601

But I guess that system could use the current one and leaderboard the new one. Or if not, just keep it as it is (I find it more fair though to consider ties)

**Comment by RoinujNosde** [comment]
> That might not be compatible with this

That's true

**Comment by xtomyserrax** [comment]
Unless internally in the code you still consider each one separately.

So the leaderboard system just works the same but you make it visual.

So for example: 
Clan   KDR    Real Position    Visual Position
A        10       1                       1
B        10       2                       1
C        8         3                       3
D        8        4                       3
E        7         5                       5

Visual postion would be for the GUI and real position for example to this placeholder feature.

**Comment by RoinujNosde** [comment]
That seems to be the only way, because the user has to insert the position.
