### ISSUE TITLE
GUI interface applications for the confirmation of clans.

### ISSUE THREAD

**Issue by KODERSKIY** [marcelo-mason/SimpleClans#614]
Hello, I want to offer my innovation in your plugin.SimpleClans is a pretty good plugin, but there are some small things that should be improved.My proposal :
- Entering the command - / clan verifylist
- Opening the GUI menu with a list of all " NOT CONFIRMED " clans
- When you click the left mouse button on the clan, the clan automatically becomes confirmed.When you click the right mouse button, information about the clan opens.

**Comment by xtomyserrax** [comment]
Yeah this could be cool for the staff GUI! #600
