### ISSUE TITLE
Resetkdr improvements

### ISSUE THREAD

**Issue by RoinujNosde** [marcelo-mason/SimpleClans#616]
- ~~Change permission to simpleclans.vip.reset-kdr~~
- Ask for confirmation before resetting
- ~~Display price on the reset button~~

**Comment by xtomyserrax** [comment]
Could you add the same confirmation before resetting to clan disband? At least with the GUI.

You could create a confirmation menu. So for example you could confirm through there resign, disband, KDR reset

**Comment by JH3Y50N** [comment]
Uma pergunta, se o jogador tiver a permissão simpleclans.vip.reset-kdr ele poderá resetar o KDR de outros jogadores? porque eu cliquei na bigorna o plugin retornou o comando de resetar um jogador... e eu tenho um plugin próprio para resetar o KDR queria saber se poderia ser possível remover essa opção do gui

**Comment by RoinujNosde** [comment]
@JH3Y50N Players com a permissão podem apenas resetar o próprio KDR.
No momento não é possível remover a opção da GUI.
