### ISSUE TITLE
Tridente ignora o fogo amigo desabilitado 

### ISSUE THREAD

**Issue by Saybin** [marcelo-mason/SimpleClans#619]
Nunca tinha reparado isso, até que hoje um player do meu servidor veio me reportar que mesmo com ff desativado é possível dar dano em pessoas do mesmo clã utilizando tridente

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/blob/68065a3b7988e6f0d393dc816784a3621d086302/src/main/java/net/sacredlabyrinth/phaed/simpleclans/listeners/SCEntityListener.java#L282
