### ISSUE TITLE
Placing owner of a clan in the same clan will cause it to disband

### ISSUE THREAD

**Issue by f0rb1d** [marcelo-mason/SimpleClans#621]
Hi,

Thank you for your contribution! I found a bug where placing the owner of a clan to the same clan would cause it to disband.

I think this should be easy to fix since you can simply add an if check.

Yours,
A player

**Comment by RoinujNosde** [comment]
Thanks for reporting.

https://github.com/marcelo-mason/SimpleClans/blob/68065a3b7988e6f0d393dc816784a3621d086302/src/main/java/net/sacredlabyrinth/phaed/simpleclans/commands/PlaceCommand.java#L51
Checking if the clans are equal should fix it.
