### ISSUE TITLE
Clan tag below player name (nametag)

### ISSUE THREAD

**Issue by RoinujNosde** [marcelo-mason/SimpleClans#622]
![image](https://user-images.githubusercontent.com/6441328/84492343-6e9e1f00-ac7c-11ea-9998-34f38bf5a2e0.png)

**Comment by CrazyDev** [comment]
Por que você adicionou? Você pretende fazer?

**Comment by RoinujNosde** [comment]
> Por que você adicionou? Você pretende fazer?

Pretendo. Sugeriram no Discord do pl.

**Comment by RoinujNosde** [comment]
https://github.com/marcelo-mason/SimpleClans/wiki/Displaying-the-clan-tag-below-the-player's-name-(tag)
