### ISSUE TITLE
API: Event lack getHandlerList() 

### ISSUE THREAD

**Issue by lackoSK** [marcelo-mason/SimpleClans#634]
Hello,

Your [ChatEvent](https://github.com/marcelo-mason/SimpleClans/blob/master/src/main/java/net/sacredlabyrinth/phaed/simpleclans/events/ChatEvent.java) lacks a method getHandlerList() which causes issues with API and so with our plugin [ https://pastebin.com/U1CMSYCH ]

`	public static HandlerList getHandlerList() {
		return handlers;
	}`

Can you please add it? 

Thank you
Ladislav from MineAcademy.org

**Comment by RoinujNosde** [comment]
Hi,
Thanks for reporting.
Does your plugin have an option to disable the hook until this is fixed?
