### ISSUE TITLE
KDR does not work AGAIN...

### ISSUE THREAD

**Issue by JH3Y50N** [marcelo-mason/SimpleClans#636]
the player have killed and don't get kdr

0 players have the perm: simpleclans.other.kdr-exempt nothing have this perm.

![image](https://user-images.githubusercontent.com/29031972/86737375-9fb70880-c00a-11ea-8a3c-76d852891786.png)

SimpleClans version:
![image](https://user-images.githubusercontent.com/29031972/86737333-988ffa80-c00a-11ea-927e-d45d0ae76def.png)

**Comment by RoinujNosde** [comment]
Me envie a sua config.

**Comment by JH3Y50N** [comment]
> Me envie a sua config.

`safe-civilians: false
tag:
  default-color: b
  max-length: 3
  bracket:
    color: '7'
    leader-color: '4'
    left: '['
    right: ']'
  min-length: 2
  separator:
    color: '7'
    leader-color: '4'
    char: ''
settings:
  enable-gui: true
  disable-messages: true
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  mchat-integration: false
  enable-auto-groups: false
  chat-compatibility-mode: false
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: false
  display-chat-tags: false
  unrivable-clans:
  - admin
  - staff
  - mod
  - vip
  - v1p
  - adm
  - bot
  - tst
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - admin
  - staff
  - mod
  - vip
  - v1p
  - adm
  - bot
  - tst
  language: pt-br
  language-per-player: false
  disallowed-tag-colors:
  - '4'
  - '0'
  - k
  - m
  - n
  - o
  - r
  - l
  server-name: '&7[&4M&aC&7]&b'
  new-clan-verification-required: false
  allow-regroup-command: false
  allow-reset-kdr: false
  rejoin-cooldown: 60
  rejoin-cooldown-enabled: false
  online-mode: false
kdr-grinding-prevention:
  enable-max-kills: false
  max-kills-per-victim: 5
  enable-kill-delay: false
  delay-between-kills: 5
list:
  size: size
  kdr: kdr
  name: name
  founded: founded
  active: active
  asc: asc
  desc: desc
  default: kdr
commands:
  more: mais
  ally: ally
  clan: clan
  accept: aceitar
  deny: negar
  global: global
  clan_chat: .
  force-priority: true
economy:
  creation-price: 10000000
  purchase-clan-create: true
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 1000000.0
  purchase-clan-invite: true
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  home-regroup-price: 5.0
  purchase-home-regroup: false
  unique-tax-on-regroup: true
  issuer-pays-regroup: true
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
  purchase-reset-kdr: false
  reset-kdr-price: 10000.0
  purchase-member-fee-set: false
  member-fee-set-price: 1000.0
  member-fee-enabled: false
  max-member-fee: 200.0
  upkeep: 200.0
  upkeep-enabled: false
  multiply-upkeep-by-clan-size: false
  charge-upkeep-only-if-member-fee-enabled: true
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
  deny-same-ip-kills: false
clan:
  homebase-teleport-wait-secs: 3
  homebase-can-be-set-only-once: false
  min-size-to-set-rival: 3
  max-length: 32
  max-description-length: 120
  min-description-length: 10
  max-members: 15
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  percentage-online-to-demote: 100.0
  ff-on-by-default: false
  min-length: 2
  min-size-to-set-ally: 3
tasks:
  collect-upkeep:
    hour: 1
    minute: 30
  collect-upkeep-warning:
    hour: 12
    minute: 0
  collect-fee:
    hour: 1
    minute: 0
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 20
clanchat:
  enable: true
  tag-based-clan-chat: false
  announcement-color: e
  format: '&b[%clan%&b] &4<%nick-color%%player%&4> %rank%&b%message%'
  rank: '&f[%rank%&f]: '
  leader-color: '4'
  trusted-color: f
  member-color: f
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
  login-size: 6
allychat:
  enable: true
  format: '&b[Clan Ally] &4<%clan%&4> <%nick-color%%player%&4> %rank%&b%message%'
  rank: '&f[%rank%&f]: '
  leader-color: '4'
  trusted-color: f
  member-color: f
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  save-periodically: true
  save-interval: 10
  use-threads: true
  use-bungeecord: false
`

**Comment by RoinujNosde** [comment]
Acontece com todos os jogadores?

**Comment by JH3Y50N** [comment]
> Acontece com todos os jogadores?

sim todos

**Comment by RoinujNosde** [comment]
[SimpleClans-debug.zip](https://github.com/marcelo-mason/SimpleClans/files/4887461/SimpleClans-debug.zip)

Rode essa versão, depois me envie o log do server.
Adicionei uns logs no evento para ver onde está o problema.

**Comment by JH3Y50N** [comment]
> [SimpleClans-debug.zip](https://github.com/marcelo-mason/SimpleClans/files/4887461/SimpleClans-debug.zip)
> 
> Rode essa versão, depois me envie o log do server.
> Adicionei uns logs no evento para ver onde está o problema.

ok, envio amanhã porque agora o servidor está cheio... não vou reiniciar ele agora

**Comment by JH3Y50N** [comment]
> [SimpleClans-debug.zip](https://github.com/marcelo-mason/SimpleClans/files/4887461/SimpleClans-debug.zip)
> 
> Rode essa versão, depois me envie o log do server.
> Adicionei uns logs no evento para ver onde está o problema.

então depois que coloquei essa versão que você me mandou o KDR voltou a contar...

Print do seu debug
![image](https://user-images.githubusercontent.com/29031972/86990213-744f2d80-c172-11ea-98eb-33b2a918a133.png)

**Comment by RoinujNosde** [comment]
> então depois que coloquei essa versão que você me mandou o KDR voltou a contar...

Estranho, não alterei nada além de colocar o debug

**Comment by JH3Y50N** [comment]
> > então depois que coloquei essa versão que você me mandou o KDR voltou a contar...
> 
> Estranho, não alterei nada além de colocar o debug

vai entender...

**Comment by RoinujNosde** [comment]
Qual plugin de permissão você usa?

**Comment by JH3Y50N** [comment]
> Qual plugin de permissão você usa?

Pex

**Comment by RoinujNosde** [comment]
> eu neguei as perm de KDR também para os jogadores... como da outra vez

O problema ocorreu antes ou depois de negar a permissão?

**Comment by JH3Y50N** [comment]
> > eu neguei as perm de KDR também para os jogadores... como da outra vez
> 
> O problema ocorreu antes ou depois de negar a permissão?

depois.. eu botei essa versão que você me mandou e voltou ao normal...

**Comment by RoinujNosde** [comment]
Eu fiz uma alteração na versão 2.13.0 para tentar corrigir isso.
Se for possível teste sem negar a permissão para ver se o bug ainda ocorre.

**Comment by JH3Y50N** [comment]
Não é possível eu fazer o teste agora
