### ISSUE TITLE
Invalid Placeholder Registration

### ISSUE THREAD

**Issue by Sxtanna** [marcelo-mason/SimpleClans#639]
In the latest version of PAPI, (2.10.7-DEV), the alternative methods for registering placeholder expansions were removed.

Causing this NSME:
```
>.... [21:24:04 INFO]: [SimpleClans] PlaceholderAPI found. Registering hook...
>.... [21:24:04 ERROR]: Error occurred while enabling SimpleClans v2.12.2 (Is it up to date?)
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPI.registerPlaceholderHook(Ljava/lang/String;Lme/clip/placeholderapi/PlaceholderHook;)Z
at net.sacredlabyrinth.phaed.simpleclans.managers.PlaceholdersManager.setupPlaceholderAPI(PlaceholdersManager.java:59) ~[?:?]
at net.sacredlabyrinth.phaed.simpleclans.managers.PlaceholdersManager.<init>(PlaceholdersManager.java:49) ~[?:?]
at net.sacredlabyrinth.phaed.simpleclans.SimpleClans.hookIntoPAPI(SimpleClans.java:147) ~[?:?]
```

More Information about this change here: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/372#issuecomment-663791480

**Comment by Sxtanna** [comment]
It's also worth noting, there's no need for the plugin to have placeholders built in as an expansion already exists: https://github.com/Peng1104/PAPI_SimpleClans

**Comment by RoinujNosde** [comment]
> It's also worth noting, there's no need for the plugin to have placeholders built in as an expansion already exists: https://github.com/Peng1104/PAPI_SimpleClans

It's not maintained.

Thanks for reporting!
