### ISSUE TITLE
Add some basic permissions when none defined

### ISSUE THREAD

**Issue by Freddo3000** [marcelo-mason/SimpleClans#643]
It would be nice not needing a permissions manager to be able to use this plugin, and have it setup so that it can be plug n play to some degree. Right now with no permissions setup non-op users are unable to use even basic commands like `/clan` without parameters.

Going by https://github.com/marcelo-mason/SimpleClans/wiki/Permissions, ther permissions `simpleclans.leader.*`, `simpleclans.member.*` and `simpleclans.anyone.*` should ideally be available by default unless otherwise stated.

<details>
<summary>Plugins list</summary>

* **Simpleclans 2.12.1**
* **Dynmap-SimpleClans 1.4.0**
* BetterSleeping
* BigDoors
* BKCommonLib
* Brewery
* Cannons
* Chairs
* DiscordSRV
* Dynmap
* ImmersiveCampfires
* LockettePro
* LogBlock
* PwnPlantGrowth
* ShipsBukkit
* Shopkeepers
* TrainCarts
* WorldBorder
* worldedit

</details>

**Comment by RoinujNosde** [comment]
Active development is now on my fork: https://github.com/RoinujNosde/SimpleClans

**Comment by Freddo3000** [comment]
@RoinujNosde would it be possible to mark this repo as archived?

**Comment by RoinujNosde** [comment]
@Freddo3000 I don't have this kind of access.
